In [1]:
# %%
# Cell 1: Imports and Setup
import os
import sys
import time
import pickle
import logging
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.notebook import tqdm

import mlflow
import mlflow.sklearn

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import (
    RandomForestClassifier, 
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

import warnings
warnings.filterwarnings("ignore")

# Display settings
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

print("✓ All imports successful")

✓ All imports successful

In [2]:
# %%
# Cell 2: Setup Logging & Directories
OUTPUT_DIR = r"C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio"
RESULTS_DIR = os.path.join(OUTPUT_DIR, "model_results")
os.makedirs(RESULTS_DIR, exist_ok=True)

# Setup logging
log_file = os.path.join(RESULTS_DIR, f"training_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

logger.info("=" * 80)
logger.info("STARTING COMPREHENSIVE MODEL TRAINING PIPELINE (MLflow ENABLED)")
logger.info("=" * 80)

print(f"✓ Logging configured: {log_file}")
print(f"✓ Results directory: {RESULTS_DIR}")

2025-12-05 14:44:56,687 - INFO - ================================================================================
2025-12-05 14:44:56,689 - INFO - STARTING COMPREHENSIVE MODEL TRAINING PIPELINE (MLflow ENABLED)
2025-12-05 14:44:56,690 - INFO - ================================================================================
2025-12-05 14:44:56,689 - INFO - STARTING COMPREHENSIVE MODEL TRAINING PIPELINE (MLflow ENABLED)
2025-12-05 14:44:56,690 - INFO - ================================================================================
✓ Logging configured: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results\training_log_20251205_144456.log
✓ Results directory: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results
✓ Logging configured: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results\training_log_20251205_144456.log
✓ Results directory: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results

In [3]:
# %%
# Cell 3: MLflow configuration
# Set an experiment name. If it does not exist, MLflow will create it.
MLFLOW_EXPERIMENT_NAME = os.getenv('MLFLOW_EXPERIMENT_NAME', 'Forest_Audio_Experiments')
MLFLOW_TRACKING_URI = os.getenv('MLFLOW_TRACKING_URI', None)  # e.g. 'http://127.0.0.1:5000' or None for local mlruns

if MLFLOW_TRACKING_URI:
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

mlflow.set_experiment(MLFLOW_EXPERIMENT_NAME)
logger.info(f"MLflow experiment set: {MLFLOW_EXPERIMENT_NAME} | tracking_uri: {mlflow.get_tracking_uri()}")

2025/12/05 14:44:56 INFO mlflow.tracking.fluent: Experiment with name 'Forest_Audio_Experiments' does not exist. Creating a new experiment.

2025-12-05 14:44:56,769 - INFO - MLflow experiment set: Forest_Audio_Experiments | tracking_uri: file:///c:/Users/Lenovo/Documents/projects/research/Major-Project/Forest-Audio/code/mlruns

In [4]:
# %%
# Cell 4: Configuration
MFCC_LIST = [8, 16, 32, 64, 128]
RANDOM_SEED = 42

# Binary mapping for your dataset
binary_mapping = {
    0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 1, 8: 0, 9: 1,
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 17: 0,
    18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0,
    26: 0, 27: 0
}

logger.info(f"MFCC configurations to test: {MFCC_LIST}")
logger.info(f"Random seed: {RANDOM_SEED}")
logger.info(f"Binary mapping: {binary_mapping}")

2025-12-05 14:44:56,782 - INFO - MFCC configurations to test: [8, 16, 32, 64, 128]
2025-12-05 14:44:56,786 - INFO - Random seed: 42
2025-12-05 14:44:56,787 - INFO - Binary mapping: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 1, 8: 0, 9: 1, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0}
2025-12-05 14:44:56,786 - INFO - Random seed: 42
2025-12-05 14:44:56,787 - INFO - Binary mapping: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 1, 8: 0, 9: 1, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0}

In [5]:
# %%
# Cell 5: Define Model Configurations with Hyperparameters
param_grids = {
    "Logistic Regression": {
        "model": LogisticRegression(max_iter=2000, class_weight="balanced", random_state=RANDOM_SEED),
        "params": {
            "C": [0.01, 0.1, 1, 10],
            "solver": ["liblinear", "lbfgs"],
            "penalty": ["l2"]
        }
    },
    "Ridge Classifier": {
        "model": RidgeClassifier(class_weight="balanced", random_state=RANDOM_SEED),
        "params": {
            "alpha": [0.1, 1.0, 10.0],
            "solver": ["auto", "saga"]
        }
    },
    "SVM (RBF)": {
        "model": SVC(class_weight="balanced", probability=True, random_state=RANDOM_SEED),
        "params": {
            "C": [0.1, 1, 10],
            "kernel": ["rbf"],
            "gamma": ["scale", "auto"]
        }
    },
    "Linear SVM": {
        "model": LinearSVC(class_weight="balanced", max_iter=2000, random_state=RANDOM_SEED),
        "params": {
            "C": [0.1, 1, 10],
            "loss": ["hinge", "squared_hinge"]
        }
    },
    "Random Forest": {
        "model": RandomForestClassifier(class_weight="balanced", random_state=RANDOM_SEED, n_jobs=-1),
        "params": {
            "n_estimators": [100, 200, 300],
            "max_depth": [10, 20, None],
            "min_samples_split": [2, 5],
            "min_samples_leaf": [1, 2]
        }
    },
    "Extra Trees": {
        "model": ExtraTreesClassifier(class_weight="balanced", random_state=RANDOM_SEED, n_jobs=-1),
        "params": {
            "n_estimators": [100, 200],
            "max_depth": [10, 20, None],
            "min_samples_split": [2, 5]
        }
    },
    "Gradient Boosting": {
        "model": GradientBoostingClassifier(random_state=RANDOM_SEED),
        "params": {
            "n_estimators": [100, 200],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [3, 5, 7],
            "subsample": [0.8, 1.0]
        }
    },
    "XGBoost": {
        "model": XGBClassifier(
            use_label_encoder=False, 
            eval_metric="logloss", 
            random_state=RANDOM_SEED,
            n_jobs=-1
        ),
        "params": {
            "n_estimators": [100, 200],
            "max_depth": [3, 6, 10],
            "learning_rate": [0.01, 0.1, 0.2],
            "subsample": [0.8, 1.0],
            "colsample_bytree": [0.8, 1.0],
            "scale_pos_weight": [1, 2]
        }
    },
    "LightGBM": {
        "model": LGBMClassifier(
            class_weight="balanced", 
            random_state=RANDOM_SEED, 
            force_col_wise=True,
            verbose=-1
        ),
        "params": {
            "n_estimators": [100, 200],
            "num_leaves": [31, 63],
            "learning_rate": [0.01, 0.1, 0.2],
            "min_child_samples": [20, 50]
        }
    },
    "AdaBoost": {
        "model": AdaBoostClassifier(random_state=RANDOM_SEED),
        "params": {
            "n_estimators": [50, 100, 200],
            "learning_rate": [0.01, 0.1, 1.0]
        }
    },
    "Decision Tree": {
        "model": DecisionTreeClassifier(class_weight="balanced", random_state=RANDOM_SEED),
        "params": {
            "max_depth": [5, 10, 20, None],
            "min_samples_split": [2, 5, 10],
            "criterion": ["gini", "entropy"]
        }
    },
    "K-Nearest Neighbors": {
        "model": KNeighborsClassifier(n_jobs=-1),
        "params": {
            "n_neighbors": [3, 5, 7, 9],
            "weights": ["uniform", "distance"],
            "metric": ["euclidean", "manhattan"]
        }
    },
    "Naive Bayes": {
        "model": GaussianNB(),
        "params": {
            "var_smoothing": [1e-9, 1e-8, 1e-7]
        }
    },
    "MLP Neural Network": {
        "model": MLPClassifier(max_iter=1000, random_state=RANDOM_SEED),
        "params": {
            "hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "activation": ["relu", "tanh"],
            "alpha": [0.0001, 0.001],
            "learning_rate": ["constant", "adaptive"]
        }
    }
}

logger.info(f"Total models configured: {len(param_grids)}")
for model_name in param_grids.keys():
    logger.info(f"  - {model_name}")

2025-12-05 14:44:56,814 - INFO - Total models configured: 14
2025-12-05 14:44:56,818 - INFO -   - Logistic Regression
2025-12-05 14:44:56,819 - INFO -   - Ridge Classifier
2025-12-05 14:44:56,822 - INFO -   - SVM (RBF)
2025-12-05 14:44:56,818 - INFO -   - Logistic Regression
2025-12-05 14:44:56,819 - INFO -   - Ridge Classifier
2025-12-05 14:44:56,822 - INFO -   - SVM (RBF)
2025-12-05 14:44:56,823 - INFO -   - Linear SVM
2025-12-05 14:44:56,825 - INFO -   - Random Forest
2025-12-05 14:44:56,826 - INFO -   - Extra Trees
2025-12-05 14:44:56,828 - INFO -   - Gradient Boosting
2025-12-05 14:44:56,829 - INFO -   - XGBoost
2025-12-05 14:44:56,831 - INFO -   - LightGBM
2025-12-05 14:44:56,823 - INFO -   - Linear SVM
2025-12-05 14:44:56,825 - INFO -   - Random Forest
2025-12-05 14:44:56,826 - INFO -   - Extra Trees
2025-12-05 14:44:56,828 - INFO -   - Gradient Boosting
2025-12-05 14:44:56,829 - INFO -   - XGBoost
2025-12-05 14:44:56,831 - INFO -   - LightGBM
2025-12-05 14:44:56,833 - INFO -   - AdaBoost
2025-12-05 14:44:56,835 - INFO -   - Decision Tree
2025-12-05 14:44:56,836 - INFO -   - K-Nearest Neighbors
2025-12-05 14:44:56,833 - INFO -   - AdaBoost
2025-12-05 14:44:56,835 - INFO -   - Decision Tree
2025-12-05 14:44:56,836 - INFO -   - K-Nearest Neighbors
2025-12-05 14:44:56,837 - INFO -   - Naive Bayes
2025-12-05 14:44:56,839 - INFO -   - MLP Neural Network
2025-12-05 14:44:56,837 - INFO -   - Naive Bayes
2025-12-05 14:44:56,839 - INFO -   - MLP Neural Network

In [6]:
# %%
# Cell 5b: Utility Functions

def get_model_size(model):
    """Calculate model size in MB"""
    import io
    buffer = io.BytesIO()
    pickle.dump(model, buffer)
    size_bytes = buffer.tell()
    size_mb = size_bytes / (1024 * 1024)
    return size_mb


def measure_inference_time(model, X_test, n_runs=100):
    """Measure average inference time"""
    times = []
    for _ in range(n_runs):
        start = time.perf_counter()
        _ = model.predict(X_test[:100])  # predict on 100 samples
        end = time.perf_counter()
        times.append(end - start)
    return np.mean(times) * 1000  # in milliseconds


def calculate_metrics(y_true, y_pred, y_proba=None):
    """Calculate comprehensive metrics"""
    metrics = {
        'accuracy': accuracy_score(y_true, y_pred),
        'precision': precision_score(y_true, y_pred, zero_division=0),
        'recall': recall_score(y_true, y_pred, zero_division=0),
        'f1': f1_score(y_true, y_pred, zero_division=0)
    }
    
    if y_proba is not None:
        try:
            metrics['roc_auc'] = roc_auc_score(y_true, y_proba)
        except:
            metrics['roc_auc'] = np.nan
    else:
        metrics['roc_auc'] = np.nan
    
    return metrics

print("✓ Utility functions defined")

✓ Utility functions defined

In [7]:
# %%
# Cell 6: Main Training Loop with MLflow logging
all_results = []

logger.info("\n" + "=" * 80)
logger.info("STARTING TRAINING LOOP")
logger.info("=" * 80)

# Outer loop: iterate over MFCC configurations
for n_mfcc in tqdm(MFCC_LIST, desc="MFCC Configs", position=0):
    logger.info(f"\n{'='*80}")
    logger.info(f"PROCESSING n_mfcc = {n_mfcc}")
    logger.info(f"{'='*80}")
    
    # Load data for this MFCC configuration
    try:
        X_train = np.load(os.path.join(OUTPUT_DIR, f"X_train_{n_mfcc}.npy"))
        X_test = np.load(os.path.join(OUTPUT_DIR, f"X_test_{n_mfcc}.npy"))
        y_train = np.load(os.path.join(OUTPUT_DIR, "y_train.npy"))
        y_test = np.load(os.path.join(OUTPUT_DIR, "y_test.npy"))
        
        logger.info(f"Data loaded - X_train: {X_train.shape}, X_test: {X_test.shape}")
    except FileNotFoundError as e:
        logger.error(f"File not found for n_mfcc={n_mfcc}: {e}")
        continue
    
    # Apply binary mapping
    y_train_bin = np.array([binary_mapping[label] for label in y_train])
    y_test_bin = np.array([binary_mapping[label] for label in y_test])
    
    class_dist = np.bincount(y_train_bin)
    logger.info(f"Binary class distribution - Class 0: {class_dist[0]}, Class 1: {class_dist[1]}")

    # Log dataset-level info to MLflow as run tags (will be updated with each run)
    dataset_info = {
        'X_train_shape': str(X_train.shape),
        'X_test_shape': str(X_test.shape),
        'y_train_shape': str(y_train_bin.shape),
        'y_test_shape': str(y_test_bin.shape),
        'class_0_count': int(class_dist[0]),
        'class_1_count': int(class_dist[1]),
        'n_mfcc': int(n_mfcc)
    }
    
    # Inner loop: iterate over models
    for model_name, config in tqdm(param_grids.items(), 
                                    desc=f"Models (n_mfcc={n_mfcc})", 
                                    position=1, 
                                    leave=False):
        logger.info(f"\n--- Training {model_name} (n_mfcc={n_mfcc}) ---")
        
        try:
            # GridSearch with cross-validation
            grid = GridSearchCV(
                estimator=config["model"],
                param_grid=config["params"],
                scoring="f1",
                cv=3,
                n_jobs=-1,
                verbose=0
            )
            
            # Start an MLflow run per model+mfcc combination
            with mlflow.start_run(run_name=f"{model_name}_mfcc{n_mfcc}") as run:
                mlflow.set_tag("model_name", model_name)
                mlflow.set_tag("n_mfcc", n_mfcc)
                mlflow.set_tags({f"dataset_{k}": v for k, v in dataset_info.items()})
                mlflow.log_param("random_seed", RANDOM_SEED)

                # Training
                train_start = time.perf_counter()
                grid.fit(X_train, y_train_bin)
                train_end = time.perf_counter()
                train_time = train_end - train_start
                
                best_model = grid.best_estimator_
                best_params = grid.best_params_
                
                logger.info(f"Best params: {best_params}")
                logger.info(f"Training time: {train_time:.2f}s")

                # Log search/grid info
                mlflow.log_param("best_params", str(best_params))
                mlflow.log_metric("cv_best_score", float(grid.best_score_))
                mlflow.log_metric("train_time_sec", float(train_time))

                # Predictions
                y_pred = best_model.predict(X_test)
                
                # Get probability predictions if available
                y_proba = None
                if hasattr(best_model, "predict_proba"):
                    y_proba = best_model.predict_proba(X_test)[:, 1]
                elif hasattr(best_model, "decision_function"):
                    y_proba = best_model.decision_function(X_test)
                
                # Calculate metrics
                metrics = calculate_metrics(y_test_bin, y_pred, y_proba)

                # Model size
                model_size = get_model_size(best_model)
                
                # Inference time
                inference_time = measure_inference_time(best_model, X_test)

                logger.info(f"Accuracy: {metrics['accuracy']:.4f}, F1: {metrics['f1']:.4f}")
                logger.info(f"Model size: {model_size:.4f} MB")
                logger.info(f"Inference time: {inference_time:.4f} ms (per 100 samples)")

                # Log metrics to MLflow
                mlflow.log_metrics({k: float(v) if not np.isnan(v) else None for k, v in metrics.items()})
                mlflow.log_metric("model_size_mb", float(model_size))
                mlflow.log_metric("inference_time_ms_per_100_samples", float(inference_time))

                # Save model artifact to disk and to MLflow
                model_filename = os.path.join(RESULTS_DIR, f"model_{model_name.replace(' ', '_')}_{n_mfcc}.pkl")
                with open(model_filename, 'wb') as f:
                    pickle.dump(best_model, f)
                mlflow.log_artifact(model_filename, artifact_path="model_pickle")

                # Also use mlflow.sklearn to log the model (allows later loading)
                try:
                    mlflow.sklearn.log_model(best_model, artifact_path="sklearn_model")
                except Exception as e:
                    logger.warning(f"mlflow.sklearn.log_model failed: {e}")

                # Confusion matrix plot and artifact
                try:
                    cm = confusion_matrix(y_test_bin, y_pred)
                    fig_cm, ax_cm = plt.subplots(figsize=(6, 5))
                    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax_cm)
                    ax_cm.set_xlabel('Predicted')
                    ax_cm.set_ylabel('Actual')
                    ax_cm.set_title(f'Confusion Matrix: {model_name} (n_mfcc={n_mfcc})')
                    cm_path = os.path.join(RESULTS_DIR, f"cm_{model_name.replace(' ', '_')}_{n_mfcc}.png")
                    plt.savefig(cm_path, dpi=200, bbox_inches='tight')
                    plt.close(fig_cm)
                    mlflow.log_artifact(cm_path, artifact_path='plots')
                except Exception as e:
                    logger.warning(f"Could not create confusion matrix plot: {e}")

                # If available, log feature importances for tree-based models
                try:
                    if hasattr(best_model, 'feature_importances_'):
                        fi = best_model.feature_importances_
                        fi_path = os.path.join(RESULTS_DIR, f"feature_importances_{model_name.replace(' ', '_')}_{n_mfcc}.csv")
                        pd.DataFrame({'feature_index': np.arange(len(fi)), 'importance': fi}).to_csv(fi_path, index=False)
                        mlflow.log_artifact(fi_path, artifact_path='feature_importances')
                except Exception as e:
                    logger.warning(f"Could not extract feature importances: {e}")

                # Record other useful run-level info
                run_id = run.info.run_id
                mlflow.set_tag('run_id', run_id)
                mlflow.log_param('model_pickle_path', model_filename)

                # Append to results list
                result = {
                    'n_mfcc': n_mfcc,
                    'model_name': model_name,
                    'accuracy': metrics['accuracy'],
                    'precision': metrics['precision'],
                    'recall': metrics['recall'],
                    'f1': metrics['f1'],
                    'roc_auc': metrics['roc_auc'],
                    'train_time_sec': train_time,
                    'inference_time_ms': inference_time,
                    'model_size_mb': model_size,
                    'best_params': str(best_params),
                    'cv_best_score': grid.best_score_,
                    'mlflow_run_id': run_id
                }
                all_results.append(result)

        except Exception as e:
            logger.error(f"Error training {model_name} with n_mfcc={n_mfcc}: {e}")
            continue

logger.info("\n" + "=" * 80)
logger.info("TRAINING COMPLETED")
logger.info("=" * 80)

# Convert to DataFrame
results_df = pd.DataFrame(all_results)
results_df.to_csv(os.path.join(RESULTS_DIR, "all_results.csv"), index=False)
logger.info(f"Results saved to: {os.path.join(RESULTS_DIR, 'all_results.csv')}")

print("\n✓ Training loop completed!")
print(f"Total experiments: {len(results_df)}")

2025-12-05 14:44:56,913 - INFO -
================================================================================
2025-12-05 14:44:56,914 - INFO - STARTING TRAINING LOOP
2025-12-05 14:44:56,914 - INFO - STARTING TRAINING LOOP
2025-12-05 14:44:56,917 - INFO - ================================================================================
2025-12-05 14:44:56,917 - INFO - ================================================================================

MFCC Configs:   0%|          | 0/5 [00:00<?, ?it/s]

2025-12-05 14:44:56,938 - INFO -
================================================================================
2025-12-05 14:44:56,941 - INFO - PROCESSING n_mfcc = 8
2025-12-05 14:44:56,942 - INFO - ================================================================================
2025-12-05 14:44:56,949 - INFO - Data loaded - X_train: (1620, 8), X_test: (405, 8)
2025-12-05 14:44:56,952 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540
2025-12-05 14:44:56,941 - INFO - PROCESSING n_mfcc = 8
2025-12-05 14:44:56,942 - INFO - ================================================================================
2025-12-05 14:44:56,949 - INFO - Data loaded - X_train: (1620, 8), X_test: (405, 8)
2025-12-05 14:44:56,952 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540

Models (n_mfcc=8):   0%|          | 0/14 [00:00<?, ?it/s]

2025-12-05 14:44:56,971 - INFO -
--- Training Logistic Regression (n_mfcc=8) ---
2025-12-05 14:45:12,315 - INFO - Best params: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
2025-12-05 14:45:12,321 - INFO - Training time: 14.93s
2025-12-05 14:45:12,315 - INFO - Best params: {'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}
2025-12-05 14:45:12,321 - INFO - Training time: 14.93s
2025-12-05 14:45:12,687 - INFO - Accuracy: 0.6667, F1: 0.5687
2025-12-05 14:45:12,689 - INFO - Model size: 0.0007 MB
2025-12-05 14:45:12,693 - INFO - Inference time: 0.3489 ms (per 100 samples)
2025-12-05 14:45:12,687 - INFO - Accuracy: 0.6667, F1: 0.5687
2025-12-05 14:45:12,689 - INFO - Model size: 0.0007 MB
2025-12-05 14:45:12,693 - INFO - Inference time: 0.3489 ms (per 100 samples)

2025/12/05 14:45:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:45:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:45:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:45:28,910 - INFO -
--- Training Ridge Classifier (n_mfcc=8) ---
2025-12-05 14:45:29,058 - INFO - Best params: {'alpha': 10.0, 'solver': 'auto'}
2025-12-05 14:45:29,060 - INFO - Training time: 0.06s
2025-12-05 14:45:29,058 - INFO - Best params: {'alpha': 10.0, 'solver': 'auto'}
2025-12-05 14:45:29,060 - INFO - Training time: 0.06s
2025-12-05 14:45:29,175 - INFO - Accuracy: 0.6543, F1: 0.5652
2025-12-05 14:45:29,175 - INFO - Model size: 0.0007 MB
2025-12-05 14:45:29,175 - INFO - Inference time: 0.0838 ms (per 100 samples)
2025-12-05 14:45:29,175 - INFO - Accuracy: 0.6543, F1: 0.5652
2025-12-05 14:45:29,175 - INFO - Model size: 0.0007 MB
2025-12-05 14:45:29,175 - INFO - Inference time: 0.0838 ms (per 100 samples)

2025/12/05 14:45:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:45:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:45:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:45:35,122 - INFO -
--- Training SVM (RBF) (n_mfcc=8) ---
2025-12-05 14:45:37,194 - INFO - Best params: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
2025-12-05 14:45:37,195 - INFO - Training time: 1.98s
2025-12-05 14:45:37,194 - INFO - Best params: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
2025-12-05 14:45:37,195 - INFO - Training time: 1.98s
2025-12-05 14:45:37,975 - INFO - Accuracy: 0.8148, F1: 0.7423
2025-12-05 14:45:37,977 - INFO - Model size: 0.0661 MB
2025-12-05 14:45:37,977 - INFO - Inference time: 6.2879 ms (per 100 samples)
2025-12-05 14:45:37,975 - INFO - Accuracy: 0.8148, F1: 0.7423
2025-12-05 14:45:37,977 - INFO - Model size: 0.0661 MB
2025-12-05 14:45:37,977 - INFO - Inference time: 6.2879 ms (per 100 samples)

2025/12/05 14:45:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:45:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:45:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:45:43,694 - INFO -
--- Training Linear SVM (n_mfcc=8) ---
2025-12-05 14:45:43,841 - INFO - Best params: {'C': 1, 'loss': 'hinge'}
2025-12-05 14:45:43,843 - INFO - Training time: 0.07s
2025-12-05 14:45:43,841 - INFO - Best params: {'C': 1, 'loss': 'hinge'}
2025-12-05 14:45:43,843 - INFO - Training time: 0.07s
2025-12-05 14:45:43,932 - INFO - Accuracy: 0.6593, F1: 0.5660
2025-12-05 14:45:43,932 - INFO - Model size: 0.0006 MB
2025-12-05 14:45:43,932 - INFO - Inference time: 0.1051 ms (per 100 samples)
2025-12-05 14:45:43,932 - INFO - Accuracy: 0.6593, F1: 0.5660
2025-12-05 14:45:43,932 - INFO - Model size: 0.0006 MB
2025-12-05 14:45:43,932 - INFO - Inference time: 0.1051 ms (per 100 samples)

2025/12/05 14:45:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:45:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:45:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:45:49,847 - INFO -
--- Training Random Forest (n_mfcc=8) ---
2025-12-05 14:46:06,590 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
2025-12-05 14:46:06,594 - INFO - Training time: 16.66s
2025-12-05 14:46:06,590 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
2025-12-05 14:46:06,594 - INFO - Training time: 16.66s
2025-12-05 14:46:10,677 - INFO - Accuracy: 0.8148, F1: 0.7059
2025-12-05 14:46:10,678 - INFO - Model size: 1.5335 MB
2025-12-05 14:46:10,679 - INFO - Inference time: 37.9663 ms (per 100 samples)
2025-12-05 14:46:10,677 - INFO - Accuracy: 0.8148, F1: 0.7059
2025-12-05 14:46:10,678 - INFO - Model size: 1.5335 MB
2025-12-05 14:46:10,679 - INFO - Inference time: 37.9663 ms (per 100 samples)

2025/12/05 14:46:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:46:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:46:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:46:16,049 - INFO -
--- Training Extra Trees (n_mfcc=8) ---
2025-12-05 14:46:19,262 - INFO - Best params: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 14:46:19,264 - INFO - Training time: 3.14s
2025-12-05 14:46:19,262 - INFO - Best params: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 14:46:19,264 - INFO - Training time: 3.14s
2025-12-05 14:46:25,025 - INFO - Accuracy: 0.8099, F1: 0.6957
2025-12-05 14:46:25,028 - INFO - Model size: 12.7085 MB
2025-12-05 14:46:25,028 - INFO - Inference time: 55.4835 ms (per 100 samples)
2025-12-05 14:46:25,025 - INFO - Accuracy: 0.8099, F1: 0.6957
2025-12-05 14:46:25,028 - INFO - Model size: 12.7085 MB
2025-12-05 14:46:25,028 - INFO - Inference time: 55.4835 ms (per 100 samples)

2025/12/05 14:46:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:46:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:46:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:46:31,196 - INFO -
--- Training Gradient Boosting (n_mfcc=8) ---
2025-12-05 14:46:56,909 - INFO - Best params: {'learning_rate': 0.2, 'max_depth': 7, 'n_estimators': 200, 'subsample': 0.8}
2025-12-05 14:46:56,909 - INFO - Training time: 25.62s
2025-12-05 14:46:56,909 - INFO - Best params: {'learning_rate': 0.2, 'max_depth': 7, 'n_estimators': 200, 'subsample': 0.8}
2025-12-05 14:46:56,909 - INFO - Training time: 25.62s
2025-12-05 14:46:57,132 - INFO - Accuracy: 0.8000, F1: 0.6639
2025-12-05 14:46:57,134 - INFO - Model size: 1.9398 MB
2025-12-05 14:46:57,136 - INFO - Inference time: 1.2953 ms (per 100 samples)
2025-12-05 14:46:57,132 - INFO - Accuracy: 0.8000, F1: 0.6639
2025-12-05 14:46:57,134 - INFO - Model size: 1.9398 MB
2025-12-05 14:46:57,136 - INFO - Inference time: 1.2953 ms (per 100 samples)

2025/12/05 14:46:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:47:02 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:47:02 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:47:03,139 - INFO -
--- Training XGBoost (n_mfcc=8) ---
2025-12-05 14:47:20,542 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 100, 'scale_pos_weight': 2, 'subsample': 0.8}
2025-12-05 14:47:20,543 - INFO - Training time: 17.32s
2025-12-05 14:47:20,542 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 100, 'scale_pos_weight': 2, 'subsample': 0.8}
2025-12-05 14:47:20,543 - INFO - Training time: 17.32s
2025-12-05 14:47:20,780 - INFO - Accuracy: 0.8025, F1: 0.6947
2025-12-05 14:47:20,782 - INFO - Model size: 0.2615 MB
2025-12-05 14:47:20,782 - INFO - Inference time: 1.0762 ms (per 100 samples)
2025-12-05 14:47:20,780 - INFO - Accuracy: 0.8025, F1: 0.6947
2025-12-05 14:47:20,782 - INFO - Model size: 0.2615 MB
2025-12-05 14:47:20,782 - INFO - Inference time: 1.0762 ms (per 100 samples)

2025/12/05 14:47:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:47:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:47:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:47:26,632 - INFO -
--- Training LightGBM (n_mfcc=8) ---
2025-12-05 14:47:39,612 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 14:47:39,612 - INFO - Training time: 12.90s
2025-12-05 14:47:39,612 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 14:47:39,612 - INFO - Training time: 12.90s
2025-12-05 14:47:39,863 - INFO - Accuracy: 0.8074, F1: 0.6880
2025-12-05 14:47:39,863 - INFO - Model size: 0.5434 MB
2025-12-05 14:47:39,863 - INFO - Inference time: 1.5616 ms (per 100 samples)
2025-12-05 14:47:39,863 - INFO - Accuracy: 0.8074, F1: 0.6880
2025-12-05 14:47:39,863 - INFO - Model size: 0.5434 MB
2025-12-05 14:47:39,863 - INFO - Inference time: 1.5616 ms (per 100 samples)

2025/12/05 14:47:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:47:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:47:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:47:45,908 - INFO -
--- Training AdaBoost (n_mfcc=8) ---
2025-12-05 14:47:49,030 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 14:47:49,032 - INFO - Training time: 3.04s
2025-12-05 14:47:49,030 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 14:47:49,032 - INFO - Training time: 3.04s
2025-12-05 14:47:51,069 - INFO - Accuracy: 0.7407, F1: 0.5455
2025-12-05 14:47:51,070 - INFO - Model size: 0.1068 MB
2025-12-05 14:47:51,072 - INFO - Inference time: 18.7756 ms (per 100 samples)
2025-12-05 14:47:51,069 - INFO - Accuracy: 0.7407, F1: 0.5455
2025-12-05 14:47:51,070 - INFO - Model size: 0.1068 MB
2025-12-05 14:47:51,072 - INFO - Inference time: 18.7756 ms (per 100 samples)

2025/12/05 14:47:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:47:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:47:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:47:56,284 - INFO -
--- Training Decision Tree (n_mfcc=8) ---
2025-12-05 14:47:56,606 - INFO - Best params: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 14:47:56,607 - INFO - Training time: 0.25s
2025-12-05 14:47:56,606 - INFO - Best params: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 14:47:56,607 - INFO - Training time: 0.25s
2025-12-05 14:47:56,700 - INFO - Accuracy: 0.7259, F1: 0.6476
2025-12-05 14:47:56,701 - INFO - Model size: 0.0146 MB
2025-12-05 14:47:56,702 - INFO - Inference time: 0.1352 ms (per 100 samples)
2025-12-05 14:47:56,700 - INFO - Accuracy: 0.7259, F1: 0.6476
2025-12-05 14:47:56,701 - INFO - Model size: 0.0146 MB
2025-12-05 14:47:56,702 - INFO - Inference time: 0.1352 ms (per 100 samples)

2025/12/05 14:47:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:48:01 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:48:01 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:48:02,068 - INFO -
--- Training K-Nearest Neighbors (n_mfcc=8) ---
2025-12-05 14:48:02,529 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 14:48:02,529 - INFO - Training time: 0.39s
2025-12-05 14:48:02,529 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 14:48:02,529 - INFO - Training time: 0.39s
2025-12-05 14:48:05,005 - INFO - Accuracy: 0.8247, F1: 0.7300
2025-12-05 14:48:05,007 - INFO - Model size: 0.1838 MB
2025-12-05 14:48:05,008 - INFO - Inference time: 23.4689 ms (per 100 samples)
2025-12-05 14:48:05,005 - INFO - Accuracy: 0.8247, F1: 0.7300
2025-12-05 14:48:05,007 - INFO - Model size: 0.1838 MB
2025-12-05 14:48:05,008 - INFO - Inference time: 23.4689 ms (per 100 samples)

2025/12/05 14:48:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:48:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:48:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:48:10,010 - INFO -
--- Training Naive Bayes (n_mfcc=8) ---
2025-12-05 14:48:10,111 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 14:48:10,111 - INFO - Training time: 0.03s
2025-12-05 14:48:10,111 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 14:48:10,111 - INFO - Training time: 0.03s
2025-12-05 14:48:10,211 - INFO - Accuracy: 0.7259, F1: 0.4249
2025-12-05 14:48:10,213 - INFO - Model size: 0.0008 MB
2025-12-05 14:48:10,214 - INFO - Inference time: 0.1614 ms (per 100 samples)
2025-12-05 14:48:10,211 - INFO - Accuracy: 0.7259, F1: 0.4249
2025-12-05 14:48:10,213 - INFO - Model size: 0.0008 MB
2025-12-05 14:48:10,214 - INFO - Inference time: 0.1614 ms (per 100 samples)

2025/12/05 14:48:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:48:14 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:48:14 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:48:15,354 - INFO -
--- Training MLP Neural Network (n_mfcc=8) ---
2025-12-05 14:49:20,066 - INFO - Best params: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (64, 32), 'learning_rate': 'constant'}
2025-12-05 14:49:20,067 - INFO - Training time: 64.60s
2025-12-05 14:49:20,066 - INFO - Best params: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (64, 32), 'learning_rate': 'constant'}
2025-12-05 14:49:20,067 - INFO - Training time: 64.60s
2025-12-05 14:49:20,172 - INFO - Accuracy: 0.8049, F1: 0.7106
2025-12-05 14:49:20,174 - INFO - Model size: 0.0664 MB
2025-12-05 14:49:20,175 - INFO - Inference time: 0.1667 ms (per 100 samples)
2025-12-05 14:49:20,172 - INFO - Accuracy: 0.8049, F1: 0.7106
2025-12-05 14:49:20,174 - INFO - Model size: 0.0664 MB
2025-12-05 14:49:20,175 - INFO - Inference time: 0.1667 ms (per 100 samples)

2025/12/05 14:49:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:49:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:49:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:49:25,674 - INFO -
================================================================================
2025-12-05 14:49:25,676 - INFO - PROCESSING n_mfcc = 16
2025-12-05 14:49:25,678 - INFO - ================================================================================
2025-12-05 14:49:25,676 - INFO - PROCESSING n_mfcc = 16
2025-12-05 14:49:25,678 - INFO - ================================================================================
2025-12-05 14:49:25,703 - INFO - Data loaded - X_train: (1620, 16), X_test: (405, 16)
2025-12-05 14:49:25,704 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540
2025-12-05 14:49:25,703 - INFO - Data loaded - X_train: (1620, 16), X_test: (405, 16)
2025-12-05 14:49:25,704 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540

Models (n_mfcc=16):   0%|          | 0/14 [00:00<?, ?it/s]

2025-12-05 14:49:25,715 - INFO -
--- Training Logistic Regression (n_mfcc=16) ---
2025-12-05 14:49:25,898 - INFO - Best params: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
2025-12-05 14:49:25,899 - INFO - Training time: 0.06s
2025-12-05 14:49:25,898 - INFO - Best params: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
2025-12-05 14:49:25,899 - INFO - Training time: 0.06s
2025-12-05 14:49:25,991 - INFO - Accuracy: 0.6840, F1: 0.5949
2025-12-05 14:49:25,993 - INFO - Model size: 0.0008 MB
2025-12-05 14:49:25,994 - INFO - Inference time: 0.0710 ms (per 100 samples)
2025-12-05 14:49:25,991 - INFO - Accuracy: 0.6840, F1: 0.5949
2025-12-05 14:49:25,993 - INFO - Model size: 0.0008 MB
2025-12-05 14:49:25,994 - INFO - Inference time: 0.0710 ms (per 100 samples)

2025/12/05 14:49:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:49:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:49:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:49:31,678 - INFO -
--- Training Ridge Classifier (n_mfcc=16) ---
2025-12-05 14:49:31,835 - INFO - Best params: {'alpha': 0.1, 'solver': 'auto'}
2025-12-05 14:49:31,836 - INFO - Training time: 0.05s
2025-12-05 14:49:31,835 - INFO - Best params: {'alpha': 0.1, 'solver': 'auto'}
2025-12-05 14:49:31,836 - INFO - Training time: 0.05s
2025-12-05 14:49:31,916 - INFO - Accuracy: 0.6568, F1: 0.5643
2025-12-05 14:49:31,918 - INFO - Model size: 0.0008 MB
2025-12-05 14:49:31,920 - INFO - Inference time: 0.0720 ms (per 100 samples)
2025-12-05 14:49:31,916 - INFO - Accuracy: 0.6568, F1: 0.5643
2025-12-05 14:49:31,918 - INFO - Model size: 0.0008 MB
2025-12-05 14:49:31,920 - INFO - Inference time: 0.0720 ms (per 100 samples)

2025/12/05 14:49:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:49:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:49:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:49:37,367 - INFO -
--- Training SVM (RBF) (n_mfcc=16) ---
2025-12-05 14:49:38,978 - INFO - Best params: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
2025-12-05 14:49:38,979 - INFO - Training time: 1.52s
2025-12-05 14:49:38,978 - INFO - Best params: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
2025-12-05 14:49:38,979 - INFO - Training time: 1.52s
2025-12-05 14:49:39,764 - INFO - Accuracy: 0.7975, F1: 0.7267
2025-12-05 14:49:39,765 - INFO - Model size: 0.1213 MB
2025-12-05 14:49:39,766 - INFO - Inference time: 6.7642 ms (per 100 samples)
2025-12-05 14:49:39,764 - INFO - Accuracy: 0.7975, F1: 0.7267
2025-12-05 14:49:39,765 - INFO - Model size: 0.1213 MB
2025-12-05 14:49:39,766 - INFO - Inference time: 6.7642 ms (per 100 samples)

2025/12/05 14:49:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:49:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:49:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:49:45,323 - INFO -
--- Training Linear SVM (n_mfcc=16) ---
2025-12-05 14:49:45,621 - INFO - Best params: {'C': 10, 'loss': 'hinge'}
2025-12-05 14:49:45,622 - INFO - Training time: 0.17s
2025-12-05 14:49:45,621 - INFO - Best params: {'C': 10, 'loss': 'hinge'}
2025-12-05 14:49:45,622 - INFO - Training time: 0.17s
2025-12-05 14:49:45,709 - INFO - Accuracy: 0.6741, F1: 0.5769
2025-12-05 14:49:45,709 - INFO - Model size: 0.0007 MB
2025-12-05 14:49:45,710 - INFO - Inference time: 0.0893 ms (per 100 samples)
2025-12-05 14:49:45,709 - INFO - Accuracy: 0.6741, F1: 0.5769
2025-12-05 14:49:45,709 - INFO - Model size: 0.0007 MB
2025-12-05 14:49:45,710 - INFO - Inference time: 0.0893 ms (per 100 samples)

2025/12/05 14:49:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:49:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:49:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:49:51,316 - INFO -
--- Training Random Forest (n_mfcc=16) ---
2025-12-05 14:50:13,444 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 100}
2025-12-05 14:50:13,446 - INFO - Training time: 22.06s
2025-12-05 14:50:13,444 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 100}
2025-12-05 14:50:13,446 - INFO - Training time: 22.06s
2025-12-05 14:50:17,320 - INFO - Accuracy: 0.8025, F1: 0.6800
2025-12-05 14:50:17,321 - INFO - Model size: 1.3316 MB
2025-12-05 14:50:17,322 - INFO - Inference time: 36.8435 ms (per 100 samples)
2025-12-05 14:50:17,320 - INFO - Accuracy: 0.8025, F1: 0.6800
2025-12-05 14:50:17,321 - INFO - Model size: 1.3316 MB
2025-12-05 14:50:17,322 - INFO - Inference time: 36.8435 ms (per 100 samples)

2025/12/05 14:50:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:50:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:50:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:50:22,960 - INFO -
--- Training Extra Trees (n_mfcc=16) ---
2025-12-05 14:50:26,475 - INFO - Best params: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 14:50:26,478 - INFO - Training time: 3.43s
2025-12-05 14:50:26,475 - INFO - Best params: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 14:50:26,478 - INFO - Training time: 3.43s
2025-12-05 14:50:32,023 - INFO - Accuracy: 0.8395, F1: 0.7303
2025-12-05 14:50:32,025 - INFO - Model size: 10.7397 MB
2025-12-05 14:50:32,026 - INFO - Inference time: 52.9578 ms (per 100 samples)
2025-12-05 14:50:32,023 - INFO - Accuracy: 0.8395, F1: 0.7303
2025-12-05 14:50:32,025 - INFO - Model size: 10.7397 MB
2025-12-05 14:50:32,026 - INFO - Inference time: 52.9578 ms (per 100 samples)

2025/12/05 14:50:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:50:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:50:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:50:37,732 - INFO -
--- Training Gradient Boosting (n_mfcc=16) ---
2025-12-05 14:51:11,308 - INFO - Best params: {'learning_rate': 0.2, 'max_depth': 7, 'n_estimators': 100, 'subsample': 0.8}
2025-12-05 14:51:11,310 - INFO - Training time: 33.45s
2025-12-05 14:51:11,308 - INFO - Best params: {'learning_rate': 0.2, 'max_depth': 7, 'n_estimators': 100, 'subsample': 0.8}
2025-12-05 14:51:11,310 - INFO - Training time: 33.45s
2025-12-05 14:51:11,465 - INFO - Accuracy: 0.8000, F1: 0.6611
2025-12-05 14:51:11,466 - INFO - Model size: 1.0595 MB
2025-12-05 14:51:11,467 - INFO - Inference time: 0.7394 ms (per 100 samples)
2025-12-05 14:51:11,465 - INFO - Accuracy: 0.8000, F1: 0.6611
2025-12-05 14:51:11,466 - INFO - Model size: 1.0595 MB
2025-12-05 14:51:11,467 - INFO - Inference time: 0.7394 ms (per 100 samples)

2025/12/05 14:51:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:51:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:51:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:51:17,264 - INFO -
--- Training XGBoost (n_mfcc=16) ---
2025-12-05 14:51:47,467 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.2, 'max_depth': 6, 'n_estimators': 200, 'scale_pos_weight': 2, 'subsample': 1.0}
2025-12-05 14:51:47,468 - INFO - Training time: 30.12s
2025-12-05 14:51:47,467 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.2, 'max_depth': 6, 'n_estimators': 200, 'scale_pos_weight': 2, 'subsample': 1.0}
2025-12-05 14:51:47,468 - INFO - Training time: 30.12s
2025-12-05 14:51:47,745 - INFO - Accuracy: 0.8049, F1: 0.6996
2025-12-05 14:51:47,746 - INFO - Model size: 0.4046 MB
2025-12-05 14:51:47,749 - INFO - Inference time: 1.4387 ms (per 100 samples)
2025-12-05 14:51:47,745 - INFO - Accuracy: 0.8049, F1: 0.6996
2025-12-05 14:51:47,746 - INFO - Model size: 0.4046 MB
2025-12-05 14:51:47,749 - INFO - Inference time: 1.4387 ms (per 100 samples)

2025/12/05 14:51:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:51:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:51:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:51:56,827 - INFO -
--- Training LightGBM (n_mfcc=16) ---
2025-12-05 14:52:05,890 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 14:52:05,893 - INFO - Training time: 8.95s
2025-12-05 14:52:05,890 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 14:52:05,893 - INFO - Training time: 8.95s
2025-12-05 14:52:06,368 - INFO - Accuracy: 0.8148, F1: 0.7104
2025-12-05 14:52:06,371 - INFO - Model size: 0.5378 MB
2025-12-05 14:52:06,373 - INFO - Inference time: 3.4804 ms (per 100 samples)
2025-12-05 14:52:06,368 - INFO - Accuracy: 0.8148, F1: 0.7104
2025-12-05 14:52:06,371 - INFO - Model size: 0.5378 MB
2025-12-05 14:52:06,373 - INFO - Inference time: 3.4804 ms (per 100 samples)

2025/12/05 14:52:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:52:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:52:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:52:13,026 - INFO -
--- Training AdaBoost (n_mfcc=16) ---
2025-12-05 14:52:17,428 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 14:52:17,430 - INFO - Training time: 4.31s
2025-12-05 14:52:17,428 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 14:52:17,430 - INFO - Training time: 4.31s
2025-12-05 14:52:19,476 - INFO - Accuracy: 0.7383, F1: 0.5391
2025-12-05 14:52:19,479 - INFO - Model size: 0.1068 MB
2025-12-05 14:52:19,481 - INFO - Inference time: 19.3520 ms (per 100 samples)
2025-12-05 14:52:19,476 - INFO - Accuracy: 0.7383, F1: 0.5391
2025-12-05 14:52:19,479 - INFO - Model size: 0.1068 MB
2025-12-05 14:52:19,481 - INFO - Inference time: 19.3520 ms (per 100 samples)

2025/12/05 14:52:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:52:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:52:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:52:25,531 - INFO -
--- Training Decision Tree (n_mfcc=16) ---
2025-12-05 14:52:26,070 - INFO - Best params: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 14:52:26,071 - INFO - Training time: 0.46s
2025-12-05 14:52:26,070 - INFO - Best params: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 14:52:26,071 - INFO - Training time: 0.46s
2025-12-05 14:52:26,153 - INFO - Accuracy: 0.6568, F1: 0.5851
2025-12-05 14:52:26,155 - INFO - Model size: 0.0129 MB
2025-12-05 14:52:26,156 - INFO - Inference time: 0.1245 ms (per 100 samples)
2025-12-05 14:52:26,153 - INFO - Accuracy: 0.6568, F1: 0.5851
2025-12-05 14:52:26,155 - INFO - Model size: 0.0129 MB
2025-12-05 14:52:26,156 - INFO - Inference time: 0.1245 ms (per 100 samples)

2025/12/05 14:52:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:52:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:52:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:52:32,743 - INFO -
--- Training K-Nearest Neighbors (n_mfcc=16) ---
2025-12-05 14:52:33,564 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 14:52:33,566 - INFO - Training time: 0.71s
2025-12-05 14:52:33,564 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 14:52:33,566 - INFO - Training time: 0.71s
2025-12-05 14:52:33,984 - INFO - Accuracy: 0.8000, F1: 0.7033
2025-12-05 14:52:33,987 - INFO - Model size: 0.1119 MB
2025-12-05 14:52:33,989 - INFO - Inference time: 2.1954 ms (per 100 samples)
2025-12-05 14:52:33,984 - INFO - Accuracy: 0.8000, F1: 0.7033
2025-12-05 14:52:33,987 - INFO - Model size: 0.1119 MB
2025-12-05 14:52:33,989 - INFO - Inference time: 2.1954 ms (per 100 samples)

2025/12/05 14:52:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:52:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:52:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:52:41,699 - INFO -
--- Training Naive Bayes (n_mfcc=16) ---
2025-12-05 14:52:41,836 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 14:52:41,839 - INFO - Training time: 0.04s
2025-12-05 14:52:41,836 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 14:52:41,839 - INFO - Training time: 0.04s
2025-12-05 14:52:41,930 - INFO - Accuracy: 0.7185, F1: 0.4124
2025-12-05 14:52:41,931 - INFO - Model size: 0.0011 MB
2025-12-05 14:52:41,932 - INFO - Inference time: 0.1640 ms (per 100 samples)
2025-12-05 14:52:41,930 - INFO - Accuracy: 0.7185, F1: 0.4124
2025-12-05 14:52:41,931 - INFO - Model size: 0.0011 MB
2025-12-05 14:52:41,932 - INFO - Inference time: 0.1640 ms (per 100 samples)

2025/12/05 14:52:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:52:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:52:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:52:48,931 - INFO -
--- Training MLP Neural Network (n_mfcc=16) ---
2025-12-05 14:54:29,907 - INFO - Best params: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (64, 32), 'learning_rate': 'constant'}
2025-12-05 14:54:29,908 - INFO - Training time: 100.88s
2025-12-05 14:54:29,907 - INFO - Best params: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (64, 32), 'learning_rate': 'constant'}
2025-12-05 14:54:29,908 - INFO - Training time: 100.88s
2025-12-05 14:54:30,012 - INFO - Accuracy: 0.8420, F1: 0.7460
2025-12-05 14:54:30,013 - INFO - Model size: 0.0654 MB
2025-12-05 14:54:30,013 - INFO - Inference time: 0.1491 ms (per 100 samples)
2025-12-05 14:54:30,012 - INFO - Accuracy: 0.8420, F1: 0.7460
2025-12-05 14:54:30,013 - INFO - Model size: 0.0654 MB
2025-12-05 14:54:30,013 - INFO - Inference time: 0.1491 ms (per 100 samples)

2025/12/05 14:54:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:54:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:54:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:54:35,821 - INFO -
================================================================================
2025-12-05 14:54:35,823 - INFO - PROCESSING n_mfcc = 32
2025-12-05 14:54:35,824 - INFO - ================================================================================
2025-12-05 14:54:35,823 - INFO - PROCESSING n_mfcc = 32
2025-12-05 14:54:35,824 - INFO - ================================================================================
2025-12-05 14:54:35,860 - INFO - Data loaded - X_train: (1620, 32), X_test: (405, 32)
2025-12-05 14:54:35,863 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540
2025-12-05 14:54:35,860 - INFO - Data loaded - X_train: (1620, 32), X_test: (405, 32)
2025-12-05 14:54:35,863 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540

Models (n_mfcc=32):   0%|          | 0/14 [00:00<?, ?it/s]

2025-12-05 14:54:35,879 - INFO -
--- Training Logistic Regression (n_mfcc=32) ---
2025-12-05 14:54:36,225 - INFO - Best params: {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}
2025-12-05 14:54:36,226 - INFO - Training time: 0.19s
2025-12-05 14:54:36,225 - INFO - Best params: {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}
2025-12-05 14:54:36,226 - INFO - Training time: 0.19s
2025-12-05 14:54:36,355 - INFO - Accuracy: 0.6840, F1: 0.5924
2025-12-05 14:54:36,357 - INFO - Model size: 0.0009 MB
2025-12-05 14:54:36,358 - INFO - Inference time: 0.0957 ms (per 100 samples)
2025-12-05 14:54:36,355 - INFO - Accuracy: 0.6840, F1: 0.5924
2025-12-05 14:54:36,357 - INFO - Model size: 0.0009 MB
2025-12-05 14:54:36,358 - INFO - Inference time: 0.0957 ms (per 100 samples)

2025/12/05 14:54:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:54:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:54:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:54:42,419 - INFO -
--- Training Ridge Classifier (n_mfcc=32) ---
2025-12-05 14:54:42,618 - INFO - Best params: {'alpha': 1.0, 'solver': 'auto'}
2025-12-05 14:54:42,619 - INFO - Training time: 0.10s
2025-12-05 14:54:42,618 - INFO - Best params: {'alpha': 1.0, 'solver': 'auto'}
2025-12-05 14:54:42,619 - INFO - Training time: 0.10s
2025-12-05 14:54:42,717 - INFO - Accuracy: 0.6765, F1: 0.5868
2025-12-05 14:54:42,718 - INFO - Model size: 0.0008 MB
2025-12-05 14:54:42,719 - INFO - Inference time: 0.0844 ms (per 100 samples)
2025-12-05 14:54:42,717 - INFO - Accuracy: 0.6765, F1: 0.5868
2025-12-05 14:54:42,718 - INFO - Model size: 0.0008 MB
2025-12-05 14:54:42,719 - INFO - Inference time: 0.0844 ms (per 100 samples)

2025/12/05 14:54:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:54:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:54:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:54:48,776 - INFO -
--- Training SVM (RBF) (n_mfcc=32) ---
2025-12-05 14:54:51,235 - INFO - Best params: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
2025-12-05 14:54:51,237 - INFO - Training time: 2.35s
2025-12-05 14:54:51,235 - INFO - Best params: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
2025-12-05 14:54:51,237 - INFO - Training time: 2.35s
2025-12-05 14:54:52,213 - INFO - Accuracy: 0.8198, F1: 0.7491
2025-12-05 14:54:52,214 - INFO - Model size: 0.2284 MB
2025-12-05 14:54:52,216 - INFO - Inference time: 8.2850 ms (per 100 samples)
2025-12-05 14:54:52,213 - INFO - Accuracy: 0.8198, F1: 0.7491
2025-12-05 14:54:52,214 - INFO - Model size: 0.2284 MB
2025-12-05 14:54:52,216 - INFO - Inference time: 8.2850 ms (per 100 samples)

2025/12/05 14:54:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:54:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:54:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:54:58,476 - INFO -
--- Training Linear SVM (n_mfcc=32) ---
2025-12-05 14:54:58,778 - INFO - Best params: {'C': 1, 'loss': 'squared_hinge'}
2025-12-05 14:54:58,779 - INFO - Training time: 0.20s
2025-12-05 14:54:58,778 - INFO - Best params: {'C': 1, 'loss': 'squared_hinge'}
2025-12-05 14:54:58,779 - INFO - Training time: 0.20s
2025-12-05 14:54:58,876 - INFO - Accuracy: 0.6790, F1: 0.5886
2025-12-05 14:54:58,877 - INFO - Model size: 0.0008 MB
2025-12-05 14:54:58,877 - INFO - Inference time: 0.0963 ms (per 100 samples)
2025-12-05 14:54:58,876 - INFO - Accuracy: 0.6790, F1: 0.5886
2025-12-05 14:54:58,877 - INFO - Model size: 0.0008 MB
2025-12-05 14:54:58,877 - INFO - Inference time: 0.0963 ms (per 100 samples)

2025/12/05 14:54:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:55:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:55:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:55:04,927 - INFO -
--- Training Random Forest (n_mfcc=32) ---
2025-12-05 14:55:44,887 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 300}
2025-12-05 14:55:44,889 - INFO - Training time: 39.86s
2025-12-05 14:55:44,887 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 300}
2025-12-05 14:55:44,889 - INFO - Training time: 39.86s
2025-12-05 14:55:53,470 - INFO - Accuracy: 0.8025, F1: 0.6774
2025-12-05 14:55:53,472 - INFO - Model size: 4.3269 MB
2025-12-05 14:55:53,473 - INFO - Inference time: 80.9530 ms (per 100 samples)
2025-12-05 14:55:53,470 - INFO - Accuracy: 0.8025, F1: 0.6774
2025-12-05 14:55:53,472 - INFO - Model size: 4.3269 MB
2025-12-05 14:55:53,473 - INFO - Inference time: 80.9530 ms (per 100 samples)

2025/12/05 14:55:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:55:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:55:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:55:59,715 - INFO -
--- Training Extra Trees (n_mfcc=32) ---
2025-12-05 14:56:06,008 - INFO - Best params: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 100}
2025-12-05 14:56:06,009 - INFO - Training time: 6.17s
2025-12-05 14:56:06,008 - INFO - Best params: {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 100}
2025-12-05 14:56:06,009 - INFO - Training time: 6.17s
2025-12-05 14:56:09,938 - INFO - Accuracy: 0.8494, F1: 0.7490
2025-12-05 14:56:09,938 - INFO - Model size: 5.1900 MB
2025-12-05 14:56:09,938 - INFO - Inference time: 37.2341 ms (per 100 samples)
2025-12-05 14:56:09,938 - INFO - Accuracy: 0.8494, F1: 0.7490
2025-12-05 14:56:09,938 - INFO - Model size: 5.1900 MB
2025-12-05 14:56:09,938 - INFO - Inference time: 37.2341 ms (per 100 samples)

2025/12/05 14:56:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:56:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:56:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:56:16,284 - INFO -
--- Training Gradient Boosting (n_mfcc=32) ---
2025-12-05 14:57:53,115 - INFO - Best params: {'learning_rate': 0.1, 'max_depth': 7, 'n_estimators': 100, 'subsample': 0.8}
2025-12-05 14:57:53,117 - INFO - Training time: 96.72s
2025-12-05 14:57:53,115 - INFO - Best params: {'learning_rate': 0.1, 'max_depth': 7, 'n_estimators': 100, 'subsample': 0.8}
2025-12-05 14:57:53,117 - INFO - Training time: 96.72s
2025-12-05 14:57:53,326 - INFO - Accuracy: 0.8296, F1: 0.7089
2025-12-05 14:57:53,328 - INFO - Model size: 1.1941 MB
2025-12-05 14:57:53,330 - INFO - Inference time: 0.9431 ms (per 100 samples)
2025-12-05 14:57:53,326 - INFO - Accuracy: 0.8296, F1: 0.7089
2025-12-05 14:57:53,328 - INFO - Model size: 1.1941 MB
2025-12-05 14:57:53,330 - INFO - Inference time: 0.9431 ms (per 100 samples)

2025/12/05 14:57:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:57:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:57:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:58:00,322 - INFO -
--- Training XGBoost (n_mfcc=32) ---
2025-12-05 14:59:15,159 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 100, 'scale_pos_weight': 2, 'subsample': 0.8}
2025-12-05 14:59:15,161 - INFO - Training time: 74.73s
2025-12-05 14:59:15,159 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 100, 'scale_pos_weight': 2, 'subsample': 0.8}
2025-12-05 14:59:15,161 - INFO - Training time: 74.73s
2025-12-05 14:59:15,332 - INFO - Accuracy: 0.8247, F1: 0.7361
2025-12-05 14:59:15,334 - INFO - Model size: 0.2665 MB
2025-12-05 14:59:15,336 - INFO - Inference time: 0.9066 ms (per 100 samples)
2025-12-05 14:59:15,332 - INFO - Accuracy: 0.8247, F1: 0.7361
2025-12-05 14:59:15,334 - INFO - Model size: 0.2665 MB
2025-12-05 14:59:15,336 - INFO - Inference time: 0.9066 ms (per 100 samples)

2025/12/05 14:59:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:59:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:59:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:59:21,000 - INFO -
--- Training LightGBM (n_mfcc=32) ---
2025-12-05 14:59:29,602 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 14:59:29,603 - INFO - Training time: 8.51s
2025-12-05 14:59:29,602 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 14:59:29,603 - INFO - Training time: 8.51s
2025-12-05 14:59:29,890 - INFO - Accuracy: 0.8370, F1: 0.7462
2025-12-05 14:59:29,891 - INFO - Model size: 0.6677 MB
2025-12-05 14:59:29,892 - INFO - Inference time: 1.8186 ms (per 100 samples)
2025-12-05 14:59:29,890 - INFO - Accuracy: 0.8370, F1: 0.7462
2025-12-05 14:59:29,891 - INFO - Model size: 0.6677 MB
2025-12-05 14:59:29,892 - INFO - Inference time: 1.8186 ms (per 100 samples)

2025/12/05 14:59:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:59:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:59:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:59:35,519 - INFO -
--- Training AdaBoost (n_mfcc=32) ---
2025-12-05 14:59:41,087 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 14:59:41,088 - INFO - Training time: 5.48s
2025-12-05 14:59:41,087 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 14:59:41,088 - INFO - Training time: 5.48s
2025-12-05 14:59:43,613 - INFO - Accuracy: 0.7630, F1: 0.5932
2025-12-05 14:59:43,614 - INFO - Model size: 0.1068 MB
2025-12-05 14:59:43,615 - INFO - Inference time: 23.4652 ms (per 100 samples)
2025-12-05 14:59:43,613 - INFO - Accuracy: 0.7630, F1: 0.5932
2025-12-05 14:59:43,614 - INFO - Model size: 0.1068 MB
2025-12-05 14:59:43,615 - INFO - Inference time: 23.4652 ms (per 100 samples)

2025/12/05 14:59:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:59:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:59:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:59:49,471 - INFO -
--- Training Decision Tree (n_mfcc=32) ---
2025-12-05 14:59:50,674 - INFO - Best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 14:59:50,674 - INFO - Training time: 1.07s
2025-12-05 14:59:50,674 - INFO - Best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 14:59:50,674 - INFO - Training time: 1.07s
2025-12-05 14:59:50,755 - INFO - Accuracy: 0.7432, F1: 0.6486
2025-12-05 14:59:50,756 - INFO - Model size: 0.0155 MB
2025-12-05 14:59:50,757 - INFO - Inference time: 0.0894 ms (per 100 samples)
2025-12-05 14:59:50,755 - INFO - Accuracy: 0.7432, F1: 0.6486
2025-12-05 14:59:50,756 - INFO - Model size: 0.0155 MB
2025-12-05 14:59:50,757 - INFO - Inference time: 0.0894 ms (per 100 samples)

2025/12/05 14:59:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 14:59:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 14:59:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 14:59:56,335 - INFO -
--- Training K-Nearest Neighbors (n_mfcc=32) ---
2025-12-05 14:59:56,784 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 14:59:56,786 - INFO - Training time: 0.33s
2025-12-05 14:59:56,784 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 14:59:56,786 - INFO - Training time: 0.33s
2025-12-05 14:59:57,157 - INFO - Accuracy: 0.8074, F1: 0.7273
2025-12-05 14:59:57,158 - INFO - Model size: 0.2108 MB
2025-12-05 14:59:57,159 - INFO - Inference time: 2.2525 ms (per 100 samples)
2025-12-05 14:59:57,157 - INFO - Accuracy: 0.8074, F1: 0.7273
2025-12-05 14:59:57,158 - INFO - Model size: 0.2108 MB
2025-12-05 14:59:57,159 - INFO - Inference time: 2.2525 ms (per 100 samples)

2025/12/05 14:59:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:00:02 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:00:02 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:00:03,037 - INFO -
--- Training Naive Bayes (n_mfcc=32) ---
2025-12-05 15:00:03,171 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 15:00:03,173 - INFO - Training time: 0.03s
2025-12-05 15:00:03,171 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 15:00:03,173 - INFO - Training time: 0.03s
2025-12-05 15:00:03,268 - INFO - Accuracy: 0.6395, F1: 0.5466
2025-12-05 15:00:03,268 - INFO - Model size: 0.0016 MB
2025-12-05 15:00:03,269 - INFO - Inference time: 0.1553 ms (per 100 samples)
2025-12-05 15:00:03,268 - INFO - Accuracy: 0.6395, F1: 0.5466
2025-12-05 15:00:03,268 - INFO - Model size: 0.0016 MB
2025-12-05 15:00:03,269 - INFO - Inference time: 0.1553 ms (per 100 samples)

2025/12/05 15:00:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:00:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:00:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:00:08,950 - INFO -
--- Training MLP Neural Network (n_mfcc=32) ---
2025-12-05 15:01:24,632 - INFO - Best params: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (128,), 'learning_rate': 'constant'}
2025-12-05 15:01:24,633 - INFO - Training time: 75.57s
2025-12-05 15:01:24,632 - INFO - Best params: {'activation': 'tanh', 'alpha': 0.001, 'hidden_layer_sizes': (128,), 'learning_rate': 'constant'}
2025-12-05 15:01:24,633 - INFO - Training time: 75.57s
2025-12-05 15:01:24,723 - INFO - Accuracy: 0.8222, F1: 0.7372
2025-12-05 15:01:24,726 - INFO - Model size: 0.0886 MB
2025-12-05 15:01:24,728 - INFO - Inference time: 0.1957 ms (per 100 samples)
2025-12-05 15:01:24,723 - INFO - Accuracy: 0.8222, F1: 0.7372
2025-12-05 15:01:24,726 - INFO - Model size: 0.0886 MB
2025-12-05 15:01:24,728 - INFO - Inference time: 0.1957 ms (per 100 samples)

2025/12/05 15:01:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:01:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:01:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:01:30,271 - INFO -
================================================================================
2025-12-05 15:01:30,271 - INFO - PROCESSING n_mfcc = 64
2025-12-05 15:01:30,276 - INFO - ================================================================================
2025-12-05 15:01:30,271 - INFO - PROCESSING n_mfcc = 64
2025-12-05 15:01:30,276 - INFO - ================================================================================
2025-12-05 15:01:30,311 - INFO - Data loaded - X_train: (1620, 64), X_test: (405, 64)
2025-12-05 15:01:30,313 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540
2025-12-05 15:01:30,311 - INFO - Data loaded - X_train: (1620, 64), X_test: (405, 64)
2025-12-05 15:01:30,313 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540

Models (n_mfcc=64):   0%|          | 0/14 [00:00<?, ?it/s]

2025-12-05 15:01:30,313 - INFO -
--- Training Logistic Regression (n_mfcc=64) ---
2025-12-05 15:01:30,660 - INFO - Best params: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
2025-12-05 15:01:30,663 - INFO - Training time: 0.22s
2025-12-05 15:01:30,660 - INFO - Best params: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
2025-12-05 15:01:30,663 - INFO - Training time: 0.22s
2025-12-05 15:01:31,002 - INFO - Accuracy: 0.6840, F1: 0.6049
2025-12-05 15:01:31,004 - INFO - Model size: 0.0012 MB
2025-12-05 15:01:31,005 - INFO - Inference time: 0.2170 ms (per 100 samples)
2025-12-05 15:01:31,002 - INFO - Accuracy: 0.6840, F1: 0.6049
2025-12-05 15:01:31,004 - INFO - Model size: 0.0012 MB
2025-12-05 15:01:31,005 - INFO - Inference time: 0.2170 ms (per 100 samples)

2025/12/05 15:01:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:01:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:01:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:01:36,658 - INFO -
--- Training Ridge Classifier (n_mfcc=64) ---
2025-12-05 15:01:37,023 - INFO - Best params: {'alpha': 10.0, 'solver': 'saga'}
2025-12-05 15:01:37,024 - INFO - Training time: 0.27s
2025-12-05 15:01:37,023 - INFO - Best params: {'alpha': 10.0, 'solver': 'saga'}
2025-12-05 15:01:37,024 - INFO - Training time: 0.27s
2025-12-05 15:01:37,108 - INFO - Accuracy: 0.6642, F1: 0.5904
2025-12-05 15:01:37,109 - INFO - Model size: 0.0010 MB
2025-12-05 15:01:37,110 - INFO - Inference time: 0.0806 ms (per 100 samples)
2025-12-05 15:01:37,108 - INFO - Accuracy: 0.6642, F1: 0.5904
2025-12-05 15:01:37,109 - INFO - Model size: 0.0010 MB
2025-12-05 15:01:37,110 - INFO - Inference time: 0.0806 ms (per 100 samples)

2025/12/05 15:01:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:01:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:01:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:01:42,762 - INFO -
--- Training SVM (RBF) (n_mfcc=64) ---
2025-12-05 15:01:45,929 - INFO - Best params: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
2025-12-05 15:01:45,930 - INFO - Training time: 3.06s
2025-12-05 15:01:45,929 - INFO - Best params: {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
2025-12-05 15:01:45,930 - INFO - Training time: 3.06s
2025-12-05 15:01:47,065 - INFO - Accuracy: 0.7827, F1: 0.6857
2025-12-05 15:01:47,065 - INFO - Model size: 0.4959 MB
2025-12-05 15:01:47,065 - INFO - Inference time: 9.9804 ms (per 100 samples)
2025-12-05 15:01:47,065 - INFO - Accuracy: 0.7827, F1: 0.6857
2025-12-05 15:01:47,065 - INFO - Model size: 0.4959 MB
2025-12-05 15:01:47,065 - INFO - Inference time: 9.9804 ms (per 100 samples)

2025/12/05 15:01:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:01:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:01:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:01:53,618 - INFO -
--- Training Linear SVM (n_mfcc=64) ---
2025-12-05 15:01:54,275 - INFO - Best params: {'C': 1, 'loss': 'hinge'}
2025-12-05 15:01:54,275 - INFO - Training time: 0.54s
2025-12-05 15:01:54,275 - INFO - Best params: {'C': 1, 'loss': 'hinge'}
2025-12-05 15:01:54,275 - INFO - Training time: 0.54s
2025-12-05 15:01:54,353 - INFO - Accuracy: 0.6790, F1: 0.6061
2025-12-05 15:01:54,354 - INFO - Model size: 0.0011 MB
2025-12-05 15:01:54,354 - INFO - Inference time: 0.0915 ms (per 100 samples)
2025-12-05 15:01:54,353 - INFO - Accuracy: 0.6790, F1: 0.6061
2025-12-05 15:01:54,354 - INFO - Model size: 0.0011 MB
2025-12-05 15:01:54,354 - INFO - Inference time: 0.0915 ms (per 100 samples)

2025/12/05 15:01:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:02:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:02:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:02:00,478 - INFO -
--- Training Random Forest (n_mfcc=64) ---
2025-12-05 15:02:53,231 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 300}
2025-12-05 15:02:53,234 - INFO - Training time: 52.65s
2025-12-05 15:02:53,231 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 300}
2025-12-05 15:02:53,234 - INFO - Training time: 52.65s
2025-12-05 15:03:07,818 - INFO - Accuracy: 0.8123, F1: 0.6807
2025-12-05 15:03:07,819 - INFO - Model size: 4.4591 MB
2025-12-05 15:03:07,820 - INFO - Inference time: 133.8760 ms (per 100 samples)
2025-12-05 15:03:07,818 - INFO - Accuracy: 0.8123, F1: 0.6807
2025-12-05 15:03:07,819 - INFO - Model size: 4.4591 MB
2025-12-05 15:03:07,820 - INFO - Inference time: 133.8760 ms (per 100 samples)

2025/12/05 15:03:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:03:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:03:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:03:15,670 - INFO -
--- Training Extra Trees (n_mfcc=64) ---
2025-12-05 15:03:22,300 - INFO - Best params: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 200}
2025-12-05 15:03:22,302 - INFO - Training time: 6.50s
2025-12-05 15:03:22,300 - INFO - Best params: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 200}
2025-12-05 15:03:22,302 - INFO - Training time: 6.50s
2025-12-05 15:03:27,784 - INFO - Accuracy: 0.8049, F1: 0.6996
2025-12-05 15:03:27,786 - INFO - Model size: 3.6697 MB
2025-12-05 15:03:27,787 - INFO - Inference time: 51.9467 ms (per 100 samples)
2025-12-05 15:03:27,784 - INFO - Accuracy: 0.8049, F1: 0.6996
2025-12-05 15:03:27,786 - INFO - Model size: 3.6697 MB
2025-12-05 15:03:27,787 - INFO - Inference time: 51.9467 ms (per 100 samples)

2025/12/05 15:03:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:03:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:03:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:03:33,742 - INFO -
--- Training Gradient Boosting (n_mfcc=64) ---
2025-12-05 15:05:20,621 - INFO - Best params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200, 'subsample': 0.8}
2025-12-05 15:05:20,623 - INFO - Training time: 106.75s
2025-12-05 15:05:20,621 - INFO - Best params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200, 'subsample': 0.8}
2025-12-05 15:05:20,623 - INFO - Training time: 106.75s
2025-12-05 15:05:20,904 - INFO - Accuracy: 0.8469, F1: 0.7328
2025-12-05 15:05:20,905 - INFO - Model size: 0.8366 MB
2025-12-05 15:05:20,906 - INFO - Inference time: 1.6534 ms (per 100 samples)
2025-12-05 15:05:20,904 - INFO - Accuracy: 0.8469, F1: 0.7328
2025-12-05 15:05:20,905 - INFO - Model size: 0.8366 MB
2025-12-05 15:05:20,906 - INFO - Inference time: 1.6534 ms (per 100 samples)

2025/12/05 15:05:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:05:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:05:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:05:26,742 - INFO -
--- Training XGBoost (n_mfcc=64) ---
2025-12-05 15:08:29,883 - INFO - Best params: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 200, 'scale_pos_weight': 2, 'subsample': 1.0}
2025-12-05 15:08:29,887 - INFO - Training time: 183.04s
2025-12-05 15:08:29,883 - INFO - Best params: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 200, 'scale_pos_weight': 2, 'subsample': 1.0}
2025-12-05 15:08:29,887 - INFO - Training time: 183.04s
2025-12-05 15:08:30,500 - INFO - Accuracy: 0.8296, F1: 0.7206
2025-12-05 15:08:30,502 - INFO - Model size: 0.6077 MB
2025-12-05 15:08:30,505 - INFO - Inference time: 3.6771 ms (per 100 samples)
2025-12-05 15:08:30,500 - INFO - Accuracy: 0.8296, F1: 0.7206
2025-12-05 15:08:30,502 - INFO - Model size: 0.6077 MB
2025-12-05 15:08:30,505 - INFO - Inference time: 3.6771 ms (per 100 samples)

2025/12/05 15:08:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:08:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:08:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:08:39,156 - INFO -
--- Training LightGBM (n_mfcc=64) ---
2025-12-05 15:09:05,898 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 15:09:05,900 - INFO - Training time: 26.64s
2025-12-05 15:09:05,898 - INFO - Best params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 15:09:05,900 - INFO - Training time: 26.64s
2025-12-05 15:09:06,355 - INFO - Accuracy: 0.8617, F1: 0.7795
2025-12-05 15:09:06,356 - INFO - Model size: 0.6718 MB
2025-12-05 15:09:06,357 - INFO - Inference time: 2.9698 ms (per 100 samples)
2025-12-05 15:09:06,355 - INFO - Accuracy: 0.8617, F1: 0.7795
2025-12-05 15:09:06,356 - INFO - Model size: 0.6718 MB
2025-12-05 15:09:06,357 - INFO - Inference time: 2.9698 ms (per 100 samples)

2025/12/05 15:09:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:09:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:09:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:09:13,135 - INFO -
--- Training AdaBoost (n_mfcc=64) ---
2025-12-05 15:09:22,638 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 15:09:22,640 - INFO - Training time: 9.42s
2025-12-05 15:09:22,638 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 15:09:22,640 - INFO - Training time: 9.42s
2025-12-05 15:09:24,568 - INFO - Accuracy: 0.7457, F1: 0.5654
2025-12-05 15:09:24,568 - INFO - Model size: 0.1068 MB
2025-12-05 15:09:24,570 - INFO - Inference time: 18.1688 ms (per 100 samples)
2025-12-05 15:09:24,568 - INFO - Accuracy: 0.7457, F1: 0.5654
2025-12-05 15:09:24,568 - INFO - Model size: 0.1068 MB
2025-12-05 15:09:24,570 - INFO - Inference time: 18.1688 ms (per 100 samples)

2025/12/05 15:09:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:09:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:09:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:09:29,823 - INFO -
--- Training Decision Tree (n_mfcc=64) ---
2025-12-05 15:09:31,011 - INFO - Best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 15:09:31,013 - INFO - Training time: 1.11s
2025-12-05 15:09:31,011 - INFO - Best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 15:09:31,013 - INFO - Training time: 1.11s
2025-12-05 15:09:31,071 - INFO - Accuracy: 0.7235, F1: 0.6267
2025-12-05 15:09:31,072 - INFO - Model size: 0.0150 MB
2025-12-05 15:09:31,073 - INFO - Inference time: 0.0723 ms (per 100 samples)
2025-12-05 15:09:31,071 - INFO - Accuracy: 0.7235, F1: 0.6267
2025-12-05 15:09:31,072 - INFO - Model size: 0.0150 MB
2025-12-05 15:09:31,073 - INFO - Inference time: 0.0723 ms (per 100 samples)

2025/12/05 15:09:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:09:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:09:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:09:35,937 - INFO -
--- Training K-Nearest Neighbors (n_mfcc=64) ---
2025-12-05 15:09:36,240 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 15:09:36,241 - INFO - Training time: 0.21s
2025-12-05 15:09:36,240 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 15:09:36,241 - INFO - Training time: 0.21s
2025-12-05 15:09:36,522 - INFO - Accuracy: 0.7778, F1: 0.6853
2025-12-05 15:09:36,522 - INFO - Model size: 0.4085 MB
2025-12-05 15:09:36,522 - INFO - Inference time: 2.0665 ms (per 100 samples)
2025-12-05 15:09:36,522 - INFO - Accuracy: 0.7778, F1: 0.6853
2025-12-05 15:09:36,522 - INFO - Model size: 0.4085 MB
2025-12-05 15:09:36,522 - INFO - Inference time: 2.0665 ms (per 100 samples)

2025/12/05 15:09:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:09:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:09:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:09:41,690 - INFO -
--- Training Naive Bayes (n_mfcc=64) ---
2025-12-05 15:09:41,789 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 15:09:41,789 - INFO - Training time: 0.03s
2025-12-05 15:09:41,789 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 15:09:41,789 - INFO - Training time: 0.03s
2025-12-05 15:09:41,871 - INFO - Accuracy: 0.6938, F1: 0.5664
2025-12-05 15:09:41,873 - INFO - Model size: 0.0025 MB
2025-12-05 15:09:41,874 - INFO - Inference time: 0.1447 ms (per 100 samples)
2025-12-05 15:09:41,871 - INFO - Accuracy: 0.6938, F1: 0.5664
2025-12-05 15:09:41,873 - INFO - Model size: 0.0025 MB
2025-12-05 15:09:41,874 - INFO - Inference time: 0.1447 ms (per 100 samples)

2025/12/05 15:09:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:09:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:09:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:09:46,602 - INFO -
--- Training MLP Neural Network (n_mfcc=64) ---
2025-12-05 15:10:20,111 - INFO - Best params: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (128,), 'learning_rate': 'constant'}
2025-12-05 15:10:20,112 - INFO - Training time: 33.43s
2025-12-05 15:10:20,111 - INFO - Best params: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (128,), 'learning_rate': 'constant'}
2025-12-05 15:10:20,112 - INFO - Training time: 33.43s
2025-12-05 15:10:20,220 - INFO - Accuracy: 0.8272, F1: 0.7328
2025-12-05 15:10:20,223 - INFO - Model size: 0.1458 MB
2025-12-05 15:10:20,224 - INFO - Inference time: 0.3309 ms (per 100 samples)
2025-12-05 15:10:20,220 - INFO - Accuracy: 0.8272, F1: 0.7328
2025-12-05 15:10:20,223 - INFO - Model size: 0.1458 MB
2025-12-05 15:10:20,224 - INFO - Inference time: 0.3309 ms (per 100 samples)

2025/12/05 15:10:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:10:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:10:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:10:25,934 - INFO -
================================================================================
2025-12-05 15:10:25,934 - INFO - PROCESSING n_mfcc = 128
2025-12-05 15:10:25,945 - INFO - ================================================================================
2025-12-05 15:10:25,934 - INFO - PROCESSING n_mfcc = 128
2025-12-05 15:10:25,945 - INFO - ================================================================================
2025-12-05 15:10:25,977 - INFO - Data loaded - X_train: (1620, 128), X_test: (405, 128)
2025-12-05 15:10:25,977 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540
2025-12-05 15:10:25,977 - INFO - Data loaded - X_train: (1620, 128), X_test: (405, 128)
2025-12-05 15:10:25,977 - INFO - Binary class distribution - Class 0: 1080, Class 1: 540

Models (n_mfcc=128):   0%|          | 0/14 [00:00<?, ?it/s]

2025-12-05 15:10:25,990 - INFO -
--- Training Logistic Regression (n_mfcc=128) ---
2025-12-05 15:10:26,537 - INFO - Best params: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
2025-12-05 15:10:26,538 - INFO - Training time: 0.45s
2025-12-05 15:10:26,537 - INFO - Best params: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
2025-12-05 15:10:26,538 - INFO - Training time: 0.45s
2025-12-05 15:10:26,673 - INFO - Accuracy: 0.7012, F1: 0.6134
2025-12-05 15:10:26,674 - INFO - Model size: 0.0017 MB
2025-12-05 15:10:26,677 - INFO - Inference time: 0.1346 ms (per 100 samples)
2025-12-05 15:10:26,673 - INFO - Accuracy: 0.7012, F1: 0.6134
2025-12-05 15:10:26,674 - INFO - Model size: 0.0017 MB
2025-12-05 15:10:26,677 - INFO - Inference time: 0.1346 ms (per 100 samples)

2025/12/05 15:10:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:10:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:10:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:10:32,134 - INFO -
--- Training Ridge Classifier (n_mfcc=128) ---
2025-12-05 15:10:32,674 - INFO - Best params: {'alpha': 10.0, 'solver': 'auto'}
2025-12-05 15:10:32,675 - INFO - Training time: 0.44s
2025-12-05 15:10:32,674 - INFO - Best params: {'alpha': 10.0, 'solver': 'auto'}
2025-12-05 15:10:32,675 - INFO - Training time: 0.44s
2025-12-05 15:10:32,744 - INFO - Accuracy: 0.6938, F1: 0.6026
2025-12-05 15:10:32,744 - INFO - Model size: 0.0012 MB
2025-12-05 15:10:32,746 - INFO - Inference time: 0.0972 ms (per 100 samples)
2025-12-05 15:10:32,744 - INFO - Accuracy: 0.6938, F1: 0.6026
2025-12-05 15:10:32,744 - INFO - Model size: 0.0012 MB
2025-12-05 15:10:32,746 - INFO - Inference time: 0.0972 ms (per 100 samples)

2025/12/05 15:10:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:10:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:10:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:10:38,652 - INFO -
--- Training SVM (RBF) (n_mfcc=128) ---
2025-12-05 15:10:41,953 - INFO - Best params: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
2025-12-05 15:10:41,954 - INFO - Training time: 3.19s
2025-12-05 15:10:41,953 - INFO - Best params: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
2025-12-05 15:10:41,954 - INFO - Training time: 3.19s
2025-12-05 15:10:43,157 - INFO - Accuracy: 0.7951, F1: 0.6982
2025-12-05 15:10:43,158 - INFO - Model size: 1.0178 MB
2025-12-05 15:10:43,159 - INFO - Inference time: 10.4886 ms (per 100 samples)
2025-12-05 15:10:43,157 - INFO - Accuracy: 0.7951, F1: 0.6982
2025-12-05 15:10:43,158 - INFO - Model size: 1.0178 MB
2025-12-05 15:10:43,159 - INFO - Inference time: 10.4886 ms (per 100 samples)

2025/12/05 15:10:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:10:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:10:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:10:48,543 - INFO -
--- Training Linear SVM (n_mfcc=128) ---
2025-12-05 15:10:50,607 - INFO - Best params: {'C': 10, 'loss': 'hinge'}
2025-12-05 15:10:50,611 - INFO - Training time: 1.97s
2025-12-05 15:10:50,607 - INFO - Best params: {'C': 10, 'loss': 'hinge'}
2025-12-05 15:10:50,611 - INFO - Training time: 1.97s
2025-12-05 15:10:50,705 - INFO - Accuracy: 0.7136, F1: 0.6282
2025-12-05 15:10:50,705 - INFO - Model size: 0.0015 MB
2025-12-05 15:10:50,707 - INFO - Inference time: 0.1702 ms (per 100 samples)
2025-12-05 15:10:50,705 - INFO - Accuracy: 0.7136, F1: 0.6282
2025-12-05 15:10:50,705 - INFO - Model size: 0.0015 MB
2025-12-05 15:10:50,707 - INFO - Inference time: 0.1702 ms (per 100 samples)

2025/12/05 15:10:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:10:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:10:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:10:56,617 - INFO -
--- Training Random Forest (n_mfcc=128) ---
2025-12-05 15:11:56,970 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 15:11:56,970 - INFO - Training time: 60.25s
2025-12-05 15:11:56,970 - INFO - Best params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 15:11:56,970 - INFO - Training time: 60.25s
2025-12-05 15:12:02,856 - INFO - Accuracy: 0.7901, F1: 0.6473
2025-12-05 15:12:02,858 - INFO - Model size: 2.9193 MB
2025-12-05 15:12:02,860 - INFO - Inference time: 56.1856 ms (per 100 samples)
2025-12-05 15:12:02,856 - INFO - Accuracy: 0.7901, F1: 0.6473
2025-12-05 15:12:02,858 - INFO - Model size: 2.9193 MB
2025-12-05 15:12:02,860 - INFO - Inference time: 56.1856 ms (per 100 samples)

2025/12/05 15:12:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:12:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:12:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:12:09,444 - INFO -
--- Training Extra Trees (n_mfcc=128) ---
2025-12-05 15:12:16,868 - INFO - Best params: {'max_depth': 10, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 15:12:16,871 - INFO - Training time: 7.28s
2025-12-05 15:12:16,868 - INFO - Best params: {'max_depth': 10, 'min_samples_split': 5, 'n_estimators': 200}
2025-12-05 15:12:16,871 - INFO - Training time: 7.28s
2025-12-05 15:12:22,422 - INFO - Accuracy: 0.8123, F1: 0.7054
2025-12-05 15:12:22,424 - INFO - Model size: 3.3702 MB
2025-12-05 15:12:22,425 - INFO - Inference time: 53.2489 ms (per 100 samples)
2025-12-05 15:12:22,422 - INFO - Accuracy: 0.8123, F1: 0.7054
2025-12-05 15:12:22,424 - INFO - Model size: 3.3702 MB
2025-12-05 15:12:22,425 - INFO - Inference time: 53.2489 ms (per 100 samples)

2025/12/05 15:12:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:12:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:12:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:12:28,484 - INFO -
--- Training Gradient Boosting (n_mfcc=128) ---
2025-12-05 15:17:36,797 - INFO - Best params: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.8}
2025-12-05 15:17:36,799 - INFO - Training time: 308.21s
2025-12-05 15:17:36,797 - INFO - Best params: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.8}
2025-12-05 15:17:36,799 - INFO - Training time: 308.21s
2025-12-05 15:17:36,997 - INFO - Accuracy: 0.8148, F1: 0.6914
2025-12-05 15:17:36,999 - INFO - Model size: 0.1335 MB
2025-12-05 15:17:36,999 - INFO - Inference time: 0.8927 ms (per 100 samples)
2025-12-05 15:17:36,997 - INFO - Accuracy: 0.8148, F1: 0.6914
2025-12-05 15:17:36,999 - INFO - Model size: 0.1335 MB
2025-12-05 15:17:36,999 - INFO - Inference time: 0.8927 ms (per 100 samples)

2025/12/05 15:17:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:17:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:17:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:17:49,189 - INFO -
--- Training XGBoost (n_mfcc=128) ---
2025-12-05 15:23:33,888 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'scale_pos_weight': 2, 'subsample': 0.8}
2025-12-05 15:23:33,890 - INFO - Training time: 344.59s
2025-12-05 15:23:33,888 - INFO - Best params: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'scale_pos_weight': 2, 'subsample': 0.8}
2025-12-05 15:23:33,890 - INFO - Training time: 344.59s
2025-12-05 15:23:34,164 - INFO - Accuracy: 0.8296, F1: 0.7454
2025-12-05 15:23:34,166 - INFO - Model size: 0.2244 MB
2025-12-05 15:23:34,168 - INFO - Inference time: 1.3123 ms (per 100 samples)
2025-12-05 15:23:34,164 - INFO - Accuracy: 0.8296, F1: 0.7454
2025-12-05 15:23:34,166 - INFO - Model size: 0.2244 MB
2025-12-05 15:23:34,168 - INFO - Inference time: 1.3123 ms (per 100 samples)

2025/12/05 15:23:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:23:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:23:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:23:41,140 - INFO -
--- Training LightGBM (n_mfcc=128) ---
2025-12-05 15:24:22,423 - INFO - Best params: {'learning_rate': 0.2, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 15:24:22,424 - INFO - Training time: 41.18s
2025-12-05 15:24:22,423 - INFO - Best params: {'learning_rate': 0.2, 'min_child_samples': 50, 'n_estimators': 200, 'num_leaves': 31}
2025-12-05 15:24:22,424 - INFO - Training time: 41.18s
2025-12-05 15:24:22,770 - INFO - Accuracy: 0.8543, F1: 0.7649
2025-12-05 15:24:22,771 - INFO - Model size: 0.5718 MB
2025-12-05 15:24:22,772 - INFO - Inference time: 2.3910 ms (per 100 samples)
2025-12-05 15:24:22,770 - INFO - Accuracy: 0.8543, F1: 0.7649
2025-12-05 15:24:22,771 - INFO - Model size: 0.5718 MB
2025-12-05 15:24:22,772 - INFO - Inference time: 2.3910 ms (per 100 samples)

2025/12/05 15:24:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:24:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:24:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:24:29,249 - INFO -
--- Training AdaBoost (n_mfcc=128) ---
2025-12-05 15:24:55,283 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 15:24:55,284 - INFO - Training time: 25.94s
2025-12-05 15:24:55,283 - INFO - Best params: {'learning_rate': 1.0, 'n_estimators': 200}
2025-12-05 15:24:55,284 - INFO - Training time: 25.94s
2025-12-05 15:24:57,593 - INFO - Accuracy: 0.7802, F1: 0.6454
2025-12-05 15:24:57,593 - INFO - Model size: 0.1068 MB
2025-12-05 15:24:57,596 - INFO - Inference time: 21.6921 ms (per 100 samples)
2025-12-05 15:24:57,593 - INFO - Accuracy: 0.7802, F1: 0.6454
2025-12-05 15:24:57,593 - INFO - Model size: 0.1068 MB
2025-12-05 15:24:57,596 - INFO - Inference time: 21.6921 ms (per 100 samples)

2025/12/05 15:24:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:25:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:25:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:25:03,795 - INFO -
--- Training Decision Tree (n_mfcc=128) ---
2025-12-05 15:25:07,626 - INFO - Best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 15:25:07,627 - INFO - Training time: 3.73s
2025-12-05 15:25:07,626 - INFO - Best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_split': 5}
2025-12-05 15:25:07,627 - INFO - Training time: 3.73s
2025-12-05 15:25:07,712 - INFO - Accuracy: 0.6988, F1: 0.6115
2025-12-05 15:25:07,713 - INFO - Model size: 0.0161 MB
2025-12-05 15:25:07,714 - INFO - Inference time: 0.1154 ms (per 100 samples)
2025-12-05 15:25:07,712 - INFO - Accuracy: 0.6988, F1: 0.6115
2025-12-05 15:25:07,713 - INFO - Model size: 0.0161 MB
2025-12-05 15:25:07,714 - INFO - Inference time: 0.1154 ms (per 100 samples)

2025/12/05 15:25:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:25:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:25:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:25:13,704 - INFO -
--- Training K-Nearest Neighbors (n_mfcc=128) ---
2025-12-05 15:25:14,440 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 15:25:14,440 - INFO - Training time: 0.63s
2025-12-05 15:25:14,440 - INFO - Best params: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
2025-12-05 15:25:14,440 - INFO - Training time: 0.63s
2025-12-05 15:25:14,893 - INFO - Accuracy: 0.7358, F1: 0.6348
2025-12-05 15:25:14,895 - INFO - Model size: 0.8040 MB
2025-12-05 15:25:14,897 - INFO - Inference time: 3.5293 ms (per 100 samples)
2025-12-05 15:25:14,893 - INFO - Accuracy: 0.7358, F1: 0.6348
2025-12-05 15:25:14,895 - INFO - Model size: 0.8040 MB
2025-12-05 15:25:14,897 - INFO - Inference time: 3.5293 ms (per 100 samples)

2025/12/05 15:25:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:25:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:25:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:25:21,480 - INFO -
--- Training Naive Bayes (n_mfcc=128) ---
2025-12-05 15:25:21,619 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 15:25:21,620 - INFO - Training time: 0.04s
2025-12-05 15:25:21,619 - INFO - Best params: {'var_smoothing': 1e-09}
2025-12-05 15:25:21,620 - INFO - Training time: 0.04s
2025-12-05 15:25:21,733 - INFO - Accuracy: 0.7160, F1: 0.4335
2025-12-05 15:25:21,734 - INFO - Model size: 0.0045 MB
2025-12-05 15:25:21,734 - INFO - Inference time: 0.3051 ms (per 100 samples)
2025-12-05 15:25:21,733 - INFO - Accuracy: 0.7160, F1: 0.4335
2025-12-05 15:25:21,734 - INFO - Model size: 0.0045 MB
2025-12-05 15:25:21,734 - INFO - Inference time: 0.3051 ms (per 100 samples)

2025/12/05 15:25:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:25:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:25:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:25:27,522 - INFO -
--- Training MLP Neural Network (n_mfcc=128) ---
2025-12-05 15:26:08,279 - INFO - Best params: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (128,), 'learning_rate': 'constant'}
2025-12-05 15:26:08,280 - INFO - Training time: 40.64s
2025-12-05 15:26:08,279 - INFO - Best params: {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (128,), 'learning_rate': 'constant'}
2025-12-05 15:26:08,280 - INFO - Training time: 40.64s
2025-12-05 15:26:08,397 - INFO - Accuracy: 0.7926, F1: 0.6934
2025-12-05 15:26:08,398 - INFO - Model size: 0.2659 MB
2025-12-05 15:26:08,398 - INFO - Inference time: 0.4163 ms (per 100 samples)
2025-12-05 15:26:08,397 - INFO - Accuracy: 0.7926, F1: 0.6934
2025-12-05 15:26:08,398 - INFO - Model size: 0.2659 MB
2025-12-05 15:26:08,398 - INFO - Inference time: 0.4163 ms (per 100 samples)

2025/12/05 15:26:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/12/05 15:26:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/12/05 15:26:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

2025-12-05 15:26:14,263 - INFO -
================================================================================
2025-12-05 15:26:14,265 - INFO - TRAINING COMPLETED
2025-12-05 15:26:14,267 - INFO - ================================================================================
2025-12-05 15:26:14,281 - INFO - Results saved to: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results\all_results.csv
2025-12-05 15:26:14,265 - INFO - TRAINING COMPLETED
2025-12-05 15:26:14,267 - INFO - ================================================================================
2025-12-05 15:26:14,281 - INFO - Results saved to: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results\all_results.csv

✓ Training loop completed!
Total experiments: 70

✓ Training loop completed!
Total experiments: 70

In [8]:
# %%
# Cell 7: Results Summary (same as original but logs to MLflow as artifact)
print("\n" + "="*80)
print("RESULTS SUMMARY")
print("="*80)

display(results_df.head(20))

# Basic statistics
print("\nBasic Statistics:")
print(results_df[['accuracy', 'precision', 'recall', 'f1', 'roc_auc']].describe())

# Save CSV and log to MLflow
summary_csv = os.path.join(RESULTS_DIR, "all_results_summary.csv")
results_df.to_csv(summary_csv, index=False)
mlflow.log_artifact(summary_csv, artifact_path='summaries')

================================================================================
RESULTS SUMMARY
================================================================================

,n_mfcc,model_name,accuracy,precision,recall,f1,roc_auc,train_time_sec,inference_time_ms,model_size_mb,best_params,cv_best_score,mlflow_run_id
0,8,Logistic Regression,0.666667,0.500000,0.659259,0.568690,0.728038,14.925484,0.348944,0.000748,"{'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}",0.583848,c7d30579b6b24db2945091a167fb57ed
1,8,Ridge Classifier,0.654321,0.486631,0.674074,0.565217,0.727380,0.064142,0.083793,0.000733,"{'alpha': 10.0, 'solver': 'auto'}",0.584570,97a33bc0f8d7497ca1879fab5b262199
2,8,SVM (RBF),0.814815,0.692308,0.800000,0.742268,0.873114,1.984435,6.287858,0.066103,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.703533,b20de24ee31b46128952f10ecc758e79
3,8,Linear SVM,0.659259,0.491803,0.666667,0.566038,0.725021,0.066210,0.105074,0.000630,"{'C': 1, 'loss': 'hinge'}",0.583434,7b343a2f44bf4a229295f77b06d7fa0e
4,8,Random Forest,0.814815,0.750000,0.666667,0.705882,0.859890,16.659018,37.966285,1.533546,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.658185,34625c26837542af8aec899f0b81022a
5,8,Extra Trees,0.809877,0.745763,0.651852,0.695652,0.888587,3.143790,55.483500,12.708545,"{'max_depth': 20, 'min_samples_split': 5, 'n_e...",0.697898,7175b6293106450daa4e5834f3001367
6,8,Gradient Boosting,0.800000,0.754717,0.592593,0.663900,0.849630,25.622895,1.295307,1.939754,"{'learning_rate': 0.2, 'max_depth': 7, 'n_esti...",0.668980,b941d63f665042ef82e0e3414cfcde45
7,8,XGBoost,0.802469,0.716535,0.674074,0.694656,0.869273,17.322090,1.076185,0.261510,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.703091,59003e7b269147ad812cae7747523429
8,8,LightGBM,0.807407,0.747826,0.637037,0.688000,0.863292,12.896653,1.561612,0.543365,"{'learning_rate': 0.1, 'min_child_samples': 50...",0.689974,c0cbb1f60eb24268881d2fa896f9dd1c
9,8,AdaBoost,0.740741,0.656250,0.466667,0.545455,0.783745,3.042124,18.775576,0.106836,"{'learning_rate': 1.0, 'n_estimators': 200}",0.557442,ebec8500e2e44e6299fd33ba02ba5bfe
10,8,Decision Tree,0.725926,0.566667,0.755556,0.647619,0.773841,0.249871,0.135165,0.014576,"{'criterion': 'entropy', 'max_depth': 10, 'min...",0.596733,43f47002079049c2ba898b43872a9e74
11,8,K-Nearest Neighbors,0.824691,0.750000,0.711111,0.730038,0.842826,0.392024,23.468883,0.183795,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.692000,2bb496871ca548fb8606df9bb6612556
12,8,Naive Bayes,0.725926,0.706897,0.303704,0.424870,0.728340,0.025724,0.161367,0.000824,{'var_smoothing': 1e-09},0.435287,190136a9f2484e20b3b016cf560255fa
13,8,MLP Neural Network,0.804938,0.702899,0.718519,0.710623,0.860631,64.602854,0.166716,0.066386,"{'activation': 'tanh', 'alpha': 0.001, 'hidden...",0.708716,dbdfb2a92e4f49f8ba30a49361b36b71
14,16,Logistic Regression,0.683951,0.519337,0.696296,0.594937,0.742634,0.059803,0.070954,0.000809,"{'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}",0.588310,d45ab4586c1e40f597845a5385eb801b
15,16,Ridge Classifier,0.656790,0.489130,0.666667,0.564263,0.742222,0.052545,0.072007,0.000764,"{'alpha': 0.1, 'solver': 'auto'}",0.588977,042a1029dd944780ac7250e7b8cd11a6
16,16,SVM (RBF),0.797531,0.660606,0.807407,0.726667,0.878903,1.516128,6.764194,0.121328,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.699245,e6c19a314148408a9b5cfacdf728143f
17,16,Linear SVM,0.674074,0.508475,0.666667,0.576923,0.741043,0.173223,0.089271,0.000691,"{'C': 10, 'loss': 'hinge'}",0.593718,5b68fb3464d348fb9fc3369a63a71e77
18,16,Random Forest,0.802469,0.739130,0.629630,0.680000,0.859726,22.055741,36.843501,1.331633,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.646694,6f5509a9e5f54cdebd9f4ceee43dbb47
19,16,Extra Trees,0.839506,0.830189,0.651852,0.730290,0.891660,3.432657,52.957750,10.739656,"{'max_depth': 20, 'min_samples_split': 5, 'n_e...",0.678432,90e11ce0dcd449df963a4efa793d0c04

Basic Statistics:
        accuracy  precision     recall         f1    roc_auc
count  70.000000  70.000000  70.000000  70.000000  70.000000
mean    0.764586   0.665025   0.660317   0.652266   0.821691
std     0.063811   0.111446   0.101583   0.081333   0.060908
min     0.639506   0.470588   0.296296   0.412371   0.696598
25%     0.704321   0.542912   0.631481   0.592573   0.764396
50%     0.793827   0.692688   0.685185   0.678710   0.849348
75%     0.814815   0.745163   0.711111   0.710573   0.872709
max     0.861728   0.876289   0.807407   0.779528   0.908395

In [9]:
# %%
# Cell 8: Top Performing Models Overall
print("\n" + "="*80)
print("TOP 10 MODELS BY F1 SCORE")
print("="*80)

top_models = results_df.nlargest(10, 'f1')[
    ['model_name', 'n_mfcc', 'f1', 'accuracy', 'precision', 'recall', 
     'roc_auc', 'model_size_mb', 'train_time_sec', 'inference_time_ms']
]
display(top_models)

top_models.to_csv(os.path.join(RESULTS_DIR, "top_10_models.csv"), index=False)
mlflow.log_artifact(os.path.join(RESULTS_DIR, "top_10_models.csv"), artifact_path='summaries')

================================================================================
TOP 10 MODELS BY F1 SCORE
================================================================================

,model_name,n_mfcc,f1,accuracy,precision,recall,roc_auc,model_size_mb,train_time_sec,inference_time_ms
50,LightGBM,64,0.779528,0.861728,0.831933,0.733333,0.908395,0.671804,26.638164,2.969795
64,LightGBM,128,0.764940,0.854321,0.827586,0.711111,0.902524,0.571819,41.180503,2.391039
30,SVM (RBF),32,0.749141,0.819753,0.698718,0.807407,0.879698,0.228390,2.353132,8.284985
33,Extra Trees,32,0.748971,0.849383,0.842593,0.674074,0.895199,5.190002,6.173962,37.234076
36,LightGBM,32,0.746154,0.837037,0.776000,0.718519,0.904883,0.667721,8.513136,1.818632
27,MLP Neural Network,16,0.746032,0.841975,0.803419,0.696296,0.881481,0.065411,100.876922,0.149062
63,XGBoost,128,0.745387,0.829630,0.742647,0.748148,0.880439,0.224367,344.594041,1.312312
2,SVM (RBF),8,0.742268,0.814815,0.692308,0.800000,0.873114,0.066103,1.984435,6.287858
41,MLP Neural Network,32,0.737226,0.822222,0.726619,0.748148,0.884883,0.088585,75.571061,0.195656
35,XGBoost,32,0.736059,0.824691,0.738806,0.733333,0.889602,0.266471,74.725933,0.906569

In [10]:
# %%
# Cell 9: Best Model Per MFCC Configuration
print("\n" + "="*80)
print("BEST MODEL FOR EACH MFCC CONFIGURATION")
print("="*80)

best_per_mfcc = results_df.loc[results_df.groupby('n_mfcc')['f1'].idxmax()][
    ['n_mfcc', 'model_name', 'f1', 'accuracy', 'precision', 'recall', 
     'roc_auc', 'model_size_mb', 'train_time_sec', 'best_params']
]
display(best_per_mfcc)

best_per_mfcc.to_csv(os.path.join(RESULTS_DIR, "best_per_mfcc.csv"), index=False)
mlflow.log_artifact(os.path.join(RESULTS_DIR, "best_per_mfcc.csv"), artifact_path='summaries')

================================================================================
BEST MODEL FOR EACH MFCC CONFIGURATION
================================================================================

,n_mfcc,model_name,f1,accuracy,precision,recall,roc_auc,model_size_mb,train_time_sec,best_params
2,8,SVM (RBF),0.742268,0.814815,0.692308,0.800000,0.873114,0.066103,1.984435,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}"
27,16,MLP Neural Network,0.746032,0.841975,0.803419,0.696296,0.881481,0.065411,100.876922,"{'activation': 'relu', 'alpha': 0.001, 'hidden..."
30,32,SVM (RBF),0.749141,0.819753,0.698718,0.807407,0.879698,0.228390,2.353132,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}"
50,64,LightGBM,0.779528,0.861728,0.831933,0.733333,0.908395,0.671804,26.638164,"{'learning_rate': 0.1, 'min_child_samples': 20..."
64,128,LightGBM,0.764940,0.854321,0.827586,0.711111,0.902524,0.571819,41.180503,"{'learning_rate': 0.2, 'min_child_samples': 50..."

In [11]:
# %%
# Cell 10: Best Model Per Algorithm
print("\n" + "="*80)
print("BEST MFCC CONFIGURATION FOR EACH MODEL")
print("="*80)

best_per_model = results_df.loc[results_df.groupby('model_name')['f1'].idxmax()][
    ['model_name', 'n_mfcc', 'f1', 'accuracy', 'precision', 'recall', 
     'roc_auc', 'model_size_mb', 'train_time_sec', 'best_params']
]
display(best_per_model)

best_per_model.to_csv(os.path.join(RESULTS_DIR, "best_per_model.csv"), index=False)
mlflow.log_artifact(os.path.join(RESULTS_DIR, "best_per_model.csv"), artifact_path='summaries')

================================================================================
BEST MFCC CONFIGURATION FOR EACH MODEL
================================================================================

,model_name,n_mfcc,f1,accuracy,precision,recall,roc_auc,model_size_mb,train_time_sec,best_params
65,AdaBoost,128,0.645418,0.780247,0.698276,0.600000,0.831248,0.106836,25.937217,"{'learning_rate': 1.0, 'n_estimators': 200}"
38,Decision Tree,32,0.648649,0.743210,0.596273,0.711111,0.762579,0.015489,1.065058,"{'criterion': 'gini', 'max_depth': 10, 'min_sa..."
33,Extra Trees,32,0.748971,0.849383,0.842593,0.674074,0.895199,5.190002,6.173962,"{'max_depth': 20, 'min_samples_split': 5, 'n_e..."
48,Gradient Boosting,64,0.732759,0.846914,0.876289,0.629630,0.886941,0.836589,106.749905,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti..."
11,K-Nearest Neighbors,8,0.730038,0.824691,0.750000,0.711111,0.842826,0.183795,0.392024,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei..."
50,LightGBM,64,0.779528,0.861728,0.831933,0.733333,0.908395,0.671804,26.638164,"{'learning_rate': 0.1, 'min_child_samples': 20..."
59,Linear SVM,128,0.628205,0.713580,0.553672,0.725926,0.783841,0.001549,1.974754,"{'C': 10, 'loss': 'hinge'}"
56,Logistic Regression,128,0.613419,0.701235,0.539326,0.711111,0.783100,0.001677,0.446239,"{'C': 0.1, 'penalty': 'l2', 'solver': 'libline..."
27,MLP Neural Network,16,0.746032,0.841975,0.803419,0.696296,0.881481,0.065411,100.876922,"{'activation': 'relu', 'alpha': 0.001, 'hidden..."
54,Naive Bayes,64,0.566434,0.693827,0.536424,0.600000,0.763594,0.002539,0.026146,{'var_smoothing': 1e-09}
4,Random Forest,8,0.705882,0.814815,0.750000,0.666667,0.859890,1.533546,16.659018,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_..."
57,Ridge Classifier,128,0.602564,0.693827,0.531073,0.696296,0.772894,0.001194,0.435065,"{'alpha': 10.0, 'solver': 'auto'}"
30,SVM (RBF),32,0.749141,0.819753,0.698718,0.807407,0.879698,0.228390,2.353132,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}"
63,XGBoost,128,0.745387,0.829630,0.742647,0.748148,0.880439,0.224367,344.594041,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."

In [12]:
# %%
# (Remaining visualization cells identical to original) - they create plots and log them
# For brevity these cells will generate the same set of plots and log to MLflow as artifacts.

# Example: generate performance heatmaps and log
try:
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    metrics = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']
    for idx, metric in enumerate(metrics):
        ax = axes[idx // 3, idx % 3]
        pivot = results_df.pivot_table(
            values=metric, 
            index='model_name', 
            columns='n_mfcc', 
            aggfunc='mean'
        )
        sns.heatmap(pivot, annot=True, fmt='.3f', cmap='YlGnBu', ax=ax, cbar_kws={'label': metric})
        ax.set_title(f'{metric.upper()} Across Models and MFCC Configs', fontsize=12, fontweight='bold')
        ax.set_xlabel('n_mfcc')
        ax.set_ylabel('Model')

    ax = axes[1, 2]
    pivot_size = results_df.pivot_table(
        values='model_size_mb', 
        index='model_name', 
        columns='n_mfcc', 
        aggfunc='mean'
    )
    sns.heatmap(pivot_size, annot=True, fmt='.2f', cmap='Reds', ax=ax, cbar_kws={'label': 'MB'})
    ax.set_title('Model Size (MB) Across Configs', fontsize=12, fontweight='bold')
    ax.set_xlabel('n_mfcc')
    ax.set_ylabel('Model')

    plt.tight_layout()
    heatmap_path = os.path.join(RESULTS_DIR, "performance_heatmaps.png")
    plt.savefig(heatmap_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    mlflow.log_artifact(heatmap_path, artifact_path='plots')
except Exception as e:
    logger.warning(f"Could not create heatmaps: {e}")

# You can re-run remaining visualization cells from the original script; ensure their generated files are saved into RESULTS_DIR

In [13]:
# %%
# Cell Final: Final Recommendations & Summary Report
print("\n" + "="*100)
print("FINAL RECOMMENDATIONS")
print("="*100)

recommendations = {
    "Best Overall Performance": results_df.nlargest(1, 'f1'),
    "Best Accuracy": results_df.nlargest(1, 'accuracy'),
    "Fastest Training": results_df.nsmallest(1, 'train_time_sec'),
    "Smallest Model": results_df.nsmallest(1, 'model_size_mb'),
    "Fastest Inference": results_df.nsmallest(1, 'inference_time_ms'),
    "Best Time Efficiency": results_df.nlargest(1, 'efficiency') if 'efficiency' in results_df.columns else results_df.nlargest(1, 'f1'),
    "Best Size Efficiency": results_df.nlargest(1, 'size_efficiency') if 'size_efficiency' in results_df.columns else results_df.nlargest(1, 'f1')
}

for category, model_row in recommendations.items():
    print(f"\n{category}:")
    print("-" * 100)
    model_info = model_row.iloc[0]
    print(f"  Model: {model_info['model_name']}")
    print(f"  n_mfcc: {model_info['n_mfcc']}")
    print(f"  F1 Score: {model_info['f1']:.4f}")
    print(f"  Accuracy: {model_info['accuracy']:.4f}")
    print(f"  Training Time: {model_info['train_time_sec']:.2f} sec")
    print(f"  Model Size: {model_info['model_size_mb']:.4f} MB")
    print(f"  Inference Time: {model_info['inference_time_ms']:.4f} ms")
    print(f"  Best Params: {model_info['best_params']}")

# Save recommendations
recommendations_df = pd.concat([df.assign(Category=cat) for cat, df in recommendations.items()])
recommendations_df.to_csv(os.path.join(RESULTS_DIR, "final_recommendations.csv"), index=False)
mlflow.log_artifact(os.path.join(RESULTS_DIR, "final_recommendations.csv"), artifact_path='summaries')

# Summary report
summary_report = {
    "Total Experiments": len(results_df),
    "Models Tested": results_df['model_name'].nunique(),
    "MFCC Configurations": len(MFCC_LIST),
    "Best Overall F1": results_df['f1'].max(),
    "Best Overall Accuracy": results_df['accuracy'].max(),
    "Average F1": results_df['f1'].mean(),
    "Average Accuracy": results_df['accuracy'].mean(),
    "Total Training Time (hours)": results_df['train_time_sec'].sum() / 3600,
    "Average Training Time (sec)": results_df['train_time_sec'].mean(),
    "Average Model Size (MB)": results_df['model_size_mb'].mean(),
    "Average Inference Time (ms)": results_df['inference_time_ms'].mean()
}

summary_df = pd.DataFrame([summary_report]).T
summary_df.columns = ['Value']

display(summary_df)

summary_path = os.path.join(RESULTS_DIR, "summary_report.csv")
summary_df.to_csv(summary_path)
mlflow.log_artifact(summary_path, artifact_path='summaries')

print(f"\n{'='*100}")
print("ALL RESULTS SAVED TO:")
print(f"  Directory: {RESULTS_DIR}")
print(f"  Main Results: all_results.csv")
print(f"  Top Models: top_10_models.csv")
print(f"  Best per MFCC: best_per_mfcc.csv")
print(f"  Best per Model: best_per_model.csv")
print(f"  Recommendations: final_recommendations.csv")
print(f"  Pareto Optimal: pareto_optimal_models.csv (if generated)")
print(f"  Summary Report: summary_report.csv")
print(f"  Log File: {log_file}")
print(f"{'='*100}")

logger.info("\n" + "=" * 80)
logger.info("PIPELINE COMPLETED SUCCESSFULLY (MLflow run metadata available)")
logger.info(f"Total experiments: {len(results_df)}")
logger.info(f"Results saved to: {RESULTS_DIR}")
logger.info("=" * 80)

====================================================================================================
FINAL RECOMMENDATIONS
====================================================================================================

Best Overall Performance:
----------------------------------------------------------------------------------------------------
  Model: LightGBM
  n_mfcc: 64
  F1 Score: 0.7795
  Accuracy: 0.8617
  Training Time: 26.64 sec
  Model Size: 0.6718 MB
  Inference Time: 2.9698 ms
  Best Params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}

Best Accuracy:
----------------------------------------------------------------------------------------------------
  Model: LightGBM
  n_mfcc: 64
  F1 Score: 0.7795
  Accuracy: 0.8617
  Training Time: 26.64 sec
  Model Size: 0.6718 MB
  Inference Time: 2.9698 ms
  Best Params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}

Fastest Training:
----------------------------------------------------------------------------------------------------
  Model: Naive Bayes
  n_mfcc: 8
  F1 Score: 0.4249
  Accuracy: 0.7259
  Training Time: 0.03 sec
  Model Size: 0.0008 MB
  Inference Time: 0.1614 ms
  Best Params: {'var_smoothing': 1e-09}

Smallest Model:
----------------------------------------------------------------------------------------------------
  Model: Linear SVM
  n_mfcc: 8
  F1 Score: 0.5660
  Accuracy: 0.6593
  Training Time: 0.07 sec
  Model Size: 0.0006 MB
  Inference Time: 0.1051 ms
  Best Params: {'C': 1, 'loss': 'hinge'}

Fastest Inference:
----------------------------------------------------------------------------------------------------
  Model: Logistic Regression
  n_mfcc: 16
  F1 Score: 0.5949
  Accuracy: 0.6840
  Training Time: 0.06 sec
  Model Size: 0.0008 MB
  Inference Time: 0.0710 ms
  Best Params: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}

Best Time Efficiency:
----------------------------------------------------------------------------------------------------
  Model: LightGBM
  n_mfcc: 64
  F1 Score: 0.7795
  Accuracy: 0.8617
  Training Time: 26.64 sec
  Model Size: 0.6718 MB
  Inference Time: 2.9698 ms
  Best Params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}

Best Size Efficiency:
----------------------------------------------------------------------------------------------------
  Model: LightGBM
  n_mfcc: 64
  F1 Score: 0.7795
  Accuracy: 0.8617
  Training Time: 26.64 sec
  Model Size: 0.6718 MB
  Inference Time: 2.9698 ms
  Best Params: {'learning_rate': 0.1, 'min_child_samples': 20, 'n_estimators': 200, 'num_leaves': 31}

                                 Value
Total Experiments            70.000000
Models Tested                14.000000
MFCC Configurations           5.000000
Best Overall F1               0.779528
Best Overall Accuracy         0.861728
Average F1                    0.652266
Average Accuracy              0.764586
Total Training Time (hours)   0.539141
Average Training Time (sec)  27.727277
Average Model Size (MB)       0.929761
Average Inference Time (ms)  11.488388

====================================================================================================
ALL RESULTS SAVED TO:
  Directory: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results
  Main Results: all_results.csv
  Top Models: top_10_models.csv
  Best per MFCC: best_per_mfcc.csv
  Best per Model: best_per_model.csv
  Recommendations: final_recommendations.csv
  Pareto Optimal: pareto_optimal_models.csv (if generated)
  Summary Report: summary_report.csv
  Log File: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results\training_log_20251205_144456.log
====================================================================================================
2025-12-05 15:26:20,764 - INFO -
================================================================================
2025-12-05 15:26:20,766 - INFO - PIPELINE COMPLETED SUCCESSFULLY (MLflow run metadata available)
2025-12-05 15:26:20,766 - INFO - PIPELINE COMPLETED SUCCESSFULLY (MLflow run metadata available)
2025-12-05 15:26:20,766 - INFO - Total experiments: 70
2025-12-05 15:26:20,769 - INFO - Results saved to: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results
2025-12-05 15:26:20,771 - INFO - ================================================================================
2025-12-05 15:26:20,766 - INFO - Total experiments: 70
2025-12-05 15:26:20,769 - INFO - Results saved to: C:\Users\Lenovo\Documents\projects\research\Major-Project\Forest-Audio\data\processed_audio\model_results
2025-12-05 15:26:20,771 - INFO - ================================================================================